### ISSUE TITLE
Implicitly scoped vars should be better hidden

### ISSUE THREAD

**Issue by natefaubion** [mozilla/sweet.js#115]
Right now if you declare a `match` var within a case macro, everything will break. They should probably be better hidden, as `match` is a really common var name. Even just a double underscore or something.

Are there other vars besides `match`?

**Comment by disnet** [comment]
I'm mass closing issues due to the release of 1.0 obviating lots of bugs. If you feel this issue is something we still need to address feel free to reopen.
