### ISSUE TITLE
A named function expression can not refer from outside of the function body

### ISSUE THREAD

**Issue by tuchida** [mozilla/sweet.js#121]
f.js:
```js
(function f() {
  // outer
  console.log(f.toString());
  (function f() {
    // inner
  })();
})();
```

```console.log``` print outer ```f``` .

```sh
$ node f.js
function f() {
  // outer
  console.log(f.toString());
  (function f() {
    // inner
  })();
}
```

But, sweet.js replace it with inner ```f``` .

```sh
$ ../sweet.js/bin/sjs f.js 
(function f$97() {
    // outer
    console.log(f$98.toString());
    (function f$98() {
    }());
}());
```

Different from specification of the JavaScript?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/function#Named_function_expression
> If you want to refer to the current function inside the function body, you need to create a named function expression. This name is then local only to the function body (scope).

**Comment by disnet** [comment]
I'm mass closing issues due to the release of 1.0 obviating lots of bugs. If you feel this issue is something we still need to address feel free to reopen.
