### ISSUE TITLE
syntax highlighting

### ISSUE THREAD

**Issue by jlongster** [mozilla/sweet.js#163]
One of the main downsides to using macros in JS is it breaks syntax highlighters. Do you guys have any ideas about this? There are times we can write macros that still seem like valid JS, but other times not which does bad things in editor's that expect normal JS.

Should macro libraries bundle in extensions to common highlighters (like vim, emacs, etc)?

**Comment by TGOlson** [comment]
Hey all, any new ideas or strategies for this problem? I haven't been able to find a JavaScript syntax highlighter/linter that allows me to add arbitrary characters to ignore. For example, I really want to use the contracts.js library, but can't find any way to ignore the `@` character. Has anyone found a good way to get around this problem?

**Comment by G-Rath** [comment]
I know this is nercoing a very old issue, but here's the [YouTrack issue](https://youtrack.jetbrains.com/issue/WEB-10934) for supporting sweet.js in IntelliJ.

Vote on it if you'd like to see it happen :)
