### ISSUE TITLE
Optimize garbage

### ISSUE THREAD

**Issue by natefaubion** [mozilla/sweet.js#164]
Sweet.js generates a ton of garbage. Specifically, sweet does a lot of "immutable" array reduction, wherein `concat` is called on each iteration of `reduce` (sometimes multiple times) when it could be `push`ing to the accumulator. Here's a js perf illustrating the magnitude of the difference: http://jsperf.com/reduce-push-vs-concat

This is a really straightforward fix, just tedious, but I think we would see some more gains in speed really easily.

**Comment by disnet** [comment]
I'm mass closing issues due to the release of 1.0 obviating lots of bugs. If you feel this issue is something we still need to address feel free to reopen.
