### ISSUE TITLE
Support for template strings

### ISSUE THREAD

**Issue by andreypopp** [mozilla/sweet.js#224]
Currently Sweet.js can parse [template strings](http://tc39wiki.calculist.org/es6/template-strings/) but only if there are no placeholders inside — `${...}` — otherwise it fails to parse the input.

I think template strings are an important feature which allows to embed other completely foreign grammars inside JS, like JSX or SQL.

**Comment by disnet** [comment]
I'm mass closing issues due to the release of 1.0 obviating lots of bugs. If you feel this issue is something we still need to address feel free to reopen.
