### ISSUE TITLE
Match against whitespace/whitespace-absence in patterns

### ISSUE THREAD

**Issue by andreypopp** [mozilla/sweet.js#226]
It would be nice for some sort of macros to be able to match for whitespace or for its absence. For example for CoffeeScript-y `@` which translates into `this.`.

Now I do something like this — https://github.com/andreypopp/react-macros/blob/master/index.sjs#L28

**Comment by disnet** [comment]
I'm mass closing issues due to the release of 1.0 obviating lots of bugs. If you feel this issue is something we still need to address feel free to reopen.
