### ISSUE TITLE
Multiple macros expansions with bindings results in exponential time complexity

### ISSUE THREAD

**Issue by andreypopp** [mozilla/sweet.js#232]
Using code from `master` branch.

Example macro
```
macro m {
  rule { $val:expr } => {
    var x = $val;
  }
}
```

```
m 11
m 11
m 11
m 11
m 11
m 11
m 11
m 11
```
expands in `1.04s`

While
```
m 11
m 11
m 11
m 11
m 11
m 11
m 11
m 11
m 11
m 11
m 11
m 11
m 11
m 11
m 11
m 11
```
expands in `5.34s`

And after adding just a one more `m 11`
```
m 11
m 11
m 11
m 11
m 11
m 11
m 11
m 11
m 11
m 11
m 11
m 11
m 11
m 11
m 11
m 11
m 11
```
in `10.26s`

:(

**Comment by disnet** [comment]
I'm mass closing issues due to the release of 1.0 obviating lots of bugs. If you feel this issue is something we still need to address feel free to reopen.
