### ISSUE TITLE
Documentation for raw syntax?

### ISSUE THREAD

**Issue by joelmccracken** [mozilla/sweet.js#255]
I have a very simple macro:

````
macro m {
  case {_ $x } => {
    foo = unwrapSyntax(#{$x})
    debugger 
  }
}
````

I'm trying to make sense of the contents of foo, but am having some trouble.

Is there a place where I may find either documentation on the output, or example code that manipulates it?

**Comment by disnet** [comment]
I'm mass closing issues due to the release of 1.0 obviating lots of bugs. If you feel this issue is something we still need to address feel free to reopen.
