### ISSUE TITLE
`let` uniqueness isn't preserved

### ISSUE THREAD

**Issue by natefaubion** [mozilla/sweet.js#277]
```js
{
  let a = 1;
  {
    let a = 2;
  }
}
```
```js
{
  let a$274 = 1;
  {
    let a$274 = 2;
  }
}
```

In practice, this isn't that big of a deal for the most part (it's just shadowed, and macro expansion still results in fresh names). Moving to using the definition context for let was correct, but we should be using two separate contexts for var and let as per the spec (`VarDeclaredNames` and `LexicallyDeclaredNamed`), pushing new let definition contexts for all blocks.

**Comment by disnet** [comment]
I'm mass closing issues due to the release of 1.0 obviating lots of bugs. If you feel this issue is something we still need to address feel free to reopen.
