### ISSUE TITLE
Multi token macros not working? 

### ISSUE THREAD

**Issue by jasuperior** [mozilla/sweet.js#293]
I won't be able to post a code sample at the moment since I am typing this issue from my phone, however, it's quite an easy issue to explain...

I'm trying to make an infix macro that matches "::" (no quotes). I followed previous advice to wrap multitoken macros in parens, but when I do an error which reads:

"Cannot find property 'fn' of undefined"

Appears... So there is either something I'm not understanding about multitoken macros, or the error is wwwaaaayyyy to ambiguous for me to even begin to understand from where the error could originate. Can someone shine some light on this for me pleas? To keep things simple, try to achieve the following syntax: 

Sum(a,b):: return a+b

It should evaluate to a function expression.

**Comment by disnet** [comment]
I'm mass closing issues due to the release of 1.0 obviating lots of bugs. If you feel this issue is something we still need to address feel free to reopen.
