### ISSUE TITLE
Hygiene problems with `match` var in transformer

### ISSUE THREAD

**Issue by natefaubion** [mozilla/sweet.js#299]
You can trivially break macros by just declaring a macro named `match`.

```js
macro match {
  rule {} => { OOPS }
}

macro test {
  rule { $foo }
}

test 123
```
```
ReferenceError: OOPS is not defined
    at eval (eval at <anonymous> (/Users/nathan/Sites/git/sweet.js/lib/scopedEval.js:16:69), <anonymous>:32:57)
    at expandMacro (/Users/nathan/Sites/git/sweet.js/lib/expander.js:1102:18)
```

It's breaking on the syntax generated by this chunk of code: https://github.com/mozilla/sweet.js/blob/master/macros/stxcase.js#L417

I don't know why it only breaks for `match` and not the other vars that use `name_stx` for a context.

**Comment by disnet** [comment]
I'm mass closing issues due to the release of 1.0 obviating lots of bugs. If you feel this issue is something we still need to address feel free to reopen.
