### ISSUE TITLE
--sourcemap with --module creates an invalid sourcemap and crashes

### ISSUE THREAD

**Issue by jbalogh** [mozilla/sweet.js#318]
Using @jlongster's fat arrow macro with the code `[1, 2, 3].map(x => x * x)`, an error is generated when creating the sourcemap:

```
Error: Invalid mapping: {"generated":{"line":5,"column":16},"source":"file.js","original":{"line":1,"column":-295},"name":"x$532"}
    at SourceMapGenerator_validateMapping [as _validateMapping] (/private/tmp/91d9ff781a377729a468/node_modules/sweet.js/node_modules/escodegen/node_modules/source-map/lib/source-map/source-map-generator.js:269:15)
```

The sourcemap validator balks at the negative column number in `"original":{"line":1,"column":-295}`.

Full STR and output: https://gist.github.com/jbalogh/91d9ff781a377729a468

**Comment by disnet** [comment]
I'm mass closing issues due to the release of 1.0 obviating lots of bugs. If you feel this issue is something we still need to address feel free to reopen.
