### ISSUE TITLE
Syntax given to case macros should be fully exposed

### ISSUE THREAD

**Issue by natefaubion** [mozilla/sweet.js#324]
Sometimes if you're messing with a glob of syntax that happens to have delimiters, you have to be vigilant to manually `expose` them, otherwise syntax can lose its lexical context. I would like it if syntax given to case macros were guaranteed to be fully exposed.

**Comment by disnet** [comment]
I'm mass closing issues due to the release of 1.0 obviating lots of bugs. If you feel this issue is something we still need to address feel free to reopen.
