### ISSUE TITLE
empower sjs

### ISSUE THREAD

**Issue by jlongster** [mozilla/sweet.js#333]
I've been dwelling on how we can help people use sweet.js, especially after talking with people at JSConf. There's a general notion that there needs to be "one" compiler that we can build tools around, and `sjs` definitely fits that. A few other people are working on an extensible compiler to encourage JS->JS compiling, enabling small individual extensions. This might become a project called "ES.next" or something, and I've talked with those guys (es6-module-compiler creator and others) and we are going to stay in touch.

Anyway, this got me thinking that we should make `sjs` smarter. Once we have modules, it will get a lot better. Until then, I think there are a few things we could do to encourage sweet.js to be the baseline for extending JavaScript. These features would make it so that you don't always have to hook up a grunt/gulp/etc task.

* Add a `--serve` option which fires up an express server for static files, and automatically expands JS files that are served. This would just be for local dev only, and I think the returns are huge for quickly getting started. It wouldn't be that complex.
* It might be worth considering making it possible to compile to pass a directory to `sjs` and specify an output directory.
* Lastly, a `--watch` option is also a possibility

We don't want to recreate a build system, but having some of this functionality would be really helpful to get people started quickly. I think the `--serve` is the most interesting, so at least do that. What do you think?

I might make an express middleware which automatically expands as well, but that's a separate project. This makes it easy to integrate the same feature when you have an express server.

**Comment by disnet** [comment]
I'm mass closing issues due to the release of 1.0 obviating lots of bugs. If you feel this issue is something we still need to address feel free to reopen.
