### ISSUE TITLE
stepping expansions doesn't work for `var` statements

### ISSUE THREAD

**Issue by jlongster** [mozilla/sweet.js#354]
If I have a macro named `var`, stepping through expansion doesn't seem to work. Just try to use my destructuring macro: https://github.com/jlongster/es6-macros/blob/master/macros/destructure.sjs and try to step through it.

That macro is actually throwing an error with the latest sweet, which is why I'm trying to step through it, so don't be surprised if you see the error.

**Comment by disnet** [comment]
I'm mass closing issues due to the release of 1.0 obviating lots of bugs. If you feel this issue is something we still need to address feel free to reopen.
