### ISSUE TITLE
`:expr` adds unecessary parentheses

### ISSUE THREAD

**Issue by jlongster** [mozilla/sweet.js#355]
Take this macro:

```
let var = macro {
  rule { $id:expr } => {
    var $id
  }
}

var x;
```

And run it with the flag to not parse"

```
% sjs -n 1 -p ./macros/destructure.sjs
var ( x );

```

Of course, if it tries to generate JS it errors because it hits a parens. Not sure what introduced this, but `expr` didn't use to always inject parens. It might look odd to match an expr on the decl part of a `var` statement, but that's exactly what I do with destructuring, and if it doesn't match `{}` or `[]` I just output a normal var statement, but now that's broken.

**Comment by disnet** [comment]
I'm mass closing issues due to the release of 1.0 obviating lots of bugs. If you feel this issue is something we still need to address feel free to reopen.
