### ISSUE TITLE
infix backtracing with member expressions

### ISSUE THREAD

**Issue by jlongster** [mozilla/sweet.js#363]
Is there a reason why this doesn't work?

```
macro foo {
  rule infix { $x = | $y } => {
    $x = $y
  }
}

// works
id1 = foo 1

// [macro] Macro `foo` could not be matched with `1 ...`
obj.id1 = foo 1
```

**Comment by disnet** [comment]
I'm mass closing issues due to the release of 1.0 obviating lots of bugs. If you feel this issue is something we still need to address feel free to reopen.
