### ISSUE TITLE
Any possibility to match ellipsis as array?

### ISSUE THREAD

**Issue by RReverser** [mozilla/sweet.js#367]
This is my second time trying to implement this in Sweet.js (gave up previous time and started writing own syntax with Jison), still no luck.

I need to convert following syntax:
```cpp
struct MyStruct {
  uint x;
  char y;
}
```

to something like
```javascript
function MyStruct(reader) {
  this.x = reader.read('uint');
  this.y = reader.read('char');
}
```

I'm trying to implement this with simple macro:
```javascript
macro struct {
	case {
		_ $sname:ident {
			$($ptype:ident $pname:ident) (;) ...
		}
	} => {
		return #{
		  function $sname(binary) {
			  $(this.$pname = binary.read($ptype);) ...
		  }
		}
  	}
}
```

but in this case I'm getting `uint` and `char` as identifiers, and I need them to be converted to literals.

Obviously `makeValue` would help, but in that case I need access to ellipsis as array so I could convert each `$ptype` in `$ptype:ident $pname:ident` pair to literal, put everything into an array and then just insert into function's body template.

But I didn't find any documentation on direct access to ellipsis. Is there one or am I just doing something wrong and there is simpler way of converting syntax types?

Thanks.

**Comment by disnet** [comment]
I'm mass closing issues due to the release of 1.0 obviating lots of bugs. If you feel this issue is something we still need to address feel free to reopen.
