### ISSUE TITLE
Param names used in macro not matching hygienic variants

### ISSUE THREAD

**Issue by rybosome** [mozilla/sweet.js#368]
I'm writing a macro that performs simple tailcall optimization for self-referential functions. There are still some bugs to work out in general (doesn't handle ternary expressions, for instance) but the basic part is working.

...except for references to my newly created function's params, which, when referenced via `makeIdent`, are not being rewritten to their hygienic variants.

So, given the following macro (pardon the mess, I haven't cleaned it up yet)...
```javascript
macro tailrec {
	case {$fn $name ($params...) { $body... } } => {
  
	function flatten(arr) {
		return Array.prototype.concat.apply([], arr);
	};
	
	function surroundWithWhile(ctx, stx) {
	  return [
		  makeKeyword('while', ctx),
		  makeDelim('()', [makeValue(true, ctx)], ctx),
		  makeDelim('{}', stx, ctx)
	  ];
	};
	
	function replaceSelfRecursives(ctx, params, stxs) {
		var length = stxs.length;
		var exprs = [];
		var terms = [];
		for (var i = 0; i < length; i++) {
			if (stxs[i].token.value == ',') {
				exprs.push(terms);
				terms = [];
			} else {
				terms.push(stxs[i]);
			}
		}
		if (terms.length) {
			exprs.push(terms)
		};
		var assignmentExpressions = exprs.map(function(expr, i) {
			return [].
				concat([
					params[i],
					makePunc('=', ctx)
				]).
				concat(expr).
				concat(makePunc(';', ctx));
		});
		return flatten(assignmentExpressions).
			concat([
				makeKeyword('continue', ctx),
				makePunc(';', ctx)
			]);
	};
	
	function isReturnStatement(stx) {
		return stx.token.type == parser.Token.Keyword &&
			stx.token.value == 'return';
	};
	
	function isFunctionParams(stx) {
		return stx.token.type == parser.Token.Delimiter &&
			stx.token.value == '()' &&
			stx.token.inner;
	};
	
	function getExpressionsFromFuncCall(stxs) {
		var returnStatementIx = stxs.findIndex(isReturnStatement);
		var postReturnStxs = stxs.slice(returnStatementIx);
		var functionParams =
			stxs.slice(returnStatementIx).find(isFunctionParams);
		return functionParams && functionParams.token.inner || [];
	};
	
	function isSelfRecursive(name, stxs) {
		var ix = stxs.findIndex(isReturnStatement);
		return ix != -1 &&
			stxs.length >= ix + 1 &&
			stxs[ix + 1].token.value == name;
	};
	
	function replaceReturns(ctx, params, body) {
		if (isSelfRecursive('fact', body)) {
			var returnStatementIx = body.findIndex(isReturnStatement);
			var replacementExpressions = replaceSelfRecursives(
				ctx, params, getExpressionsFromFuncCall(body));
			body.splice(returnStatementIx, replacementExpressions.length, replacementExpressions);
			var newBody = flatten(body);
			return newBody;
		} else {
			return body.map(function(s) {
				if (s.token.inner) {
					s.token.inner = replaceReturns(ctx, params, s.token.inner);
					return s;
				} else {
					return s;
				}
			});
		}
	};
	
	function getParams(params, ctx) {
		return params.filter(function(p) {
			return p.token.type == parser.Token.Identifier;
		}).
		map(function(p) {
			return makeIdent(p.token.value, ctx);
		});
	};

	var ctx = #{$fn};
	
	letstx params = getParams(#{$params...}, ctx);

	var newBody = surroundWithWhile(ctx, #{$body...});
	var newBody2 = replaceReturns(ctx, params, newBody);
	
	return [
		makeKeyword('function', ctx),
		makeDelim('()', #{$params...}, ctx),
		makeDelim('{}', newBody2, ctx)
	];
  }
}
```

It gets rewritten like so:
```javascript
// Before rewrite
var factorial = function(n) {
	var r = tailrec fact(n, acc) {
		if (n <= 1) {
			return acc;
		} else {
			return fact(n - 1, acc * n);
		}
	};
	return r(n, 1);
};

// After rewrite
var factorial = function (n) {
    var r = function (n$2, acc$2) {
        while (true) {
            if (n$2 <= 1) {
                return acc$2;
            } else {
                n$108523 = n$2 - 1;
                acc = acc$2 * n$2;
                continue;
            }
        }
    };
    return r(n, 1);
};
```

Am I doing something incorrectly, or is this indeed a bug?

[Test](http://sweetjs.org/browser/editor.html#macro%20tailrec%20{%0A%09case%20{$fn%20$name%20%28$params...%29%20{%20$body...%20}%20}%20=%3E%20{%0A%20%20%0A%09function%20flatten%28arr%29%20{%0A%09%09return%20Array.prototype.concat.apply%28[],%20arr%29;%0A%09};%0A%09%0A%09function%20surroundWithWhile%28ctx,%20stx%29%20{%0A%09%20%20return%20[%0A%09%09%20%20makeKeyword%28%27while%27,%20ctx%29,%0A%09%09%20%20makeDelim%28%27%28%29%27,%20[makeValue%28true,%20ctx%29],%20ctx%29,%0A%09%09%20%20makeDelim%28%27{}%27,%20stx,%20ctx%29%0A%09%20%20];%0A%09};%0A%09%0A%09function%20replaceSelfRecursives%28ctx,%20params,%20stxs%29%20{%0A%09%09var%20length%20=%20stxs.length;%0A%09%09var%20exprs%20=%20[];%0A%09%09var%20terms%20=%20[];%0A%09%09for%20%28var%20i%20=%200;%20i%20%3C%20length;%20i++%29%20{%0A%09%09%09if%20%28stxs[i].token.value%20==%20%27,%27%29%20{%0A%09%09%09%09exprs.push%28terms%29;%0A%09%09%09%09terms%20=%20[];%0A%09%09%09}%20else%20{%0A%09%09%09%09terms.push%28stxs[i]%29;%0A%09%09%09}%0A%09%09}%0A%09%09if%20%28terms.length%29%20{%0A%09%09%09exprs.push%28terms%29%0A%09%09};%0A%09%09var%20assignmentExpressions%20=%20exprs.map%28function%28expr,%20i%29%20{%0A%09%09%09return%20[].%0A%09%09%09%09concat%28[%0A%09%09%09%09%09params[i],%0A%09%09%09%09%09makePunc%28%27=%27,%20ctx%29%0A%09%09%09%09]%29.%0A%09%09%09%09concat%28expr%29.%0A%09%09%09%09concat%28makePunc%28%27;%27,%20ctx%29%29;%0A%09%09}%29;%0A%09%09return%20flatten%28assignmentExpressions%29.%0A%09%09%09concat%28[%0A%09%09%09%09makeKeyword%28%27continue%27,%20ctx%29,%0A%09%09%09%09makePunc%28%27;%27,%20ctx%29%0A%09%09%09]%29;%0A%09};%0A%09%0A%09function%20isReturnStatement%28stx%29%20{%0A%09%09return%20stx.token.type%20==%20parser.Token.Keyword%20&&%0A%09%09%09stx.token.value%20==%20%27return%27;%0A%09};%0A%09%0A%09function%20isFunctionParams%28stx%29%20{%0A%09%09return%20stx.token.type%20==%20parser.Token.Delimiter%20&&%0A%09%09%09stx.token.value%20==%20%27%28%29%27%20&&%0A%09%09%09stx.token.inner;%0A%09};%0A%09%0A%09function%20getExpressionsFromFuncCall%28stxs%29%20{%0A%09%09var%20returnStatementIx%20=%20stxs.findIndex%28isReturnStatement%29;%0A%09%09var%20postReturnStxs%20=%20stxs.slice%28returnStatementIx%29;%0A%09%09var%20functionParams%20=%0A%09%09%09stxs.slice%28returnStatementIx%29.find%28isFunctionParams%29;%0A%09%09return%20functionParams%20&&%20functionParams.token.inner%20||%20[];%0A%09};%0A%09%0A%09function%20isSelfRecursive%28name,%20stxs%29%20{%0A%09%09var%20ix%20=%20stxs.findIndex%28isReturnStatement%29;%0A%09%09return%20ix%20!=%20-1%20&&%0A%09%09%09stxs.length%20%3E=%20ix%20+%201%20&&%0A%09%09%09stxs[ix%20+%201].token.value%20==%20name;%0A%09};%0A%09%0A%09function%20replaceReturns%28ctx,%20params,%20body%29%20{%0A%09%09if%20%28isSelfRecursive%28%27fact%27,%20body%29%29%20{%0A%09%09%09var%20returnStatementIx%20=%20body.findIndex%28isReturnStatement%29;%0A%09%09%09var%20replacementExpressions%20=%20replaceSelfRecursives%28%0A%09%09%09%09ctx,%20params,%20getExpressionsFromFuncCall%28body%29%29;%0A%09%09%09body.splice%28returnStatementIx,%20replacementExpressions.length,%20replacementExpressions%29;%0A%09%09%09var%20newBody%20=%20flatten%28body%29;%0A%09%09%09return%20newBody;%0A%09%09}%20else%20{%0A%09%09%09return%20body.map%28function%28s%29%20{%0A%09%09%09%09if%20%28s.token.inner%29%20{%0A%09%09%09%09%09s.token.inner%20=%20replaceReturns%28ctx,%20params,%20s.token.inner%29;%0A%09%09%09%09%09return%20s;%0A%09%09%09%09}%20else%20{%0A%09%09%09%09%09return%20s;%0A%09%09%09%09}%0A%09%09%09}%29;%0A%09%09}%0A%09};%0A%09%0A%09function%20getParams%28params,%20ctx%29%20{%0A%09%09return%20params.filter%28function%28p%29%20{%0A%09%09%09return%20p.token.type%20==%20parser.Token.Identifier;%0A%09%09}%29.%0A%09%09map%28function%28p%29%20{%0A%09%09%09return%20makeIdent%28p.token.value,%20ctx%29;%0A%09%09}%29;%0A%09};%0A%0A%09var%20ctx%20=%20#{$fn};%0A%09%0A%09letstx%20params%20=%20getParams%28#{$params...},%20ctx%29;%0A%0A%09var%20newBody%20=%20surroundWithWhile%28ctx,%20#{$body...}%29;%0A%09var%20newBody2%20=%20replaceReturns%28ctx,%20params,%20newBody%29;%0A%09%0A%09return%20[%0A%09%09makeKeyword%28%27function%27,%20ctx%29,%0A%09%09makeDelim%28%27%28%29%27,%20#{$params...},%20ctx%29,%0A%09%09makeDelim%28%27{}%27,%20newBody2,%20ctx%29%0A%09];%0A%20%20}%0A}%0A%0Avar%20factorial%20=%20function%28n%29%20{%0A%09var%20r%20=%20tailrec%20fact%28n,%20acc%29%20{%0A%09%09if%20%28n%20%3C=%201%29%20{%0A%09%09%09return%20acc;%0A%09%09}%20else%20{%0A%09%09%09return%20fact%28n%20-%201,%20acc%20*%20n%29;%0A%09%09}%0A%09};%0A%09return%20r%28n,%201%29;%0A};%0A)

**Comment by disnet** [comment]
I'm mass closing issues due to the release of 1.0 obviating lots of bugs. If you feel this issue is something we still need to address feel free to reopen.
