### ISSUE TITLE
sweet.js accepts unbalanced brackets

### ISSUE THREAD

**Issue by Wilfred** [mozilla/sweet.js#385]
I was surprised to discover that sweet.js doesn't require brackets to be matched in its patterns:

```
macro swap {
    rule { ($x, $y)) } => {
        var tmp = $x;
        $x = $y;
        $y = tmp;
    }
}
```

I would have expected an error when I defined the macro. It's a little bit tricky to debug otherwise.

If I do make this mistake, I can actually call my macro with unbalanced brackets:

```
var a = 1, b = 2;
swap(a, b));
```

Is this expected behaviour?

**Comment by disnet** [comment]
I'm mass closing issues due to the release of 1.0 obviating lots of bugs. If you feel this issue is something we still need to address feel free to reopen.
