### ISSUE TITLE
Refactor `--readable-names` so we don't need escope

### ISSUE THREAD

**Issue by natefaubion** [mozilla/sweet.js#396]
We should be able to move `--readable-names` into the parser by using a modified version of `resolve` which walks the entire lexical context instead of stopping early. Basically you'd do the normal work of `resolve` but when you find a match, you'd just keep going to count how many times its shadowed and spit out the name based on that. This would have the benefit of *always* working with whatever our parser accepts, not requiring an additional pass, and always being on.

**Comment by disnet** [comment]
I'm mass closing issues due to the release of 1.0 obviating lots of bugs. If you feel this issue is something we still need to address feel free to reopen.
