### ISSUE TITLE
Serialize errors as JS objects (optional?) 

### ISSUE THREAD

**Issue by am11** [mozilla/sweet.js#403]
Currently, the exception object has XML serialized string for errors, so the downstreams need to parse it using regex. Something like:

https://github.com/madskristensen/WebEssentials2013/blob/c82a9a52816bb59fb10833811c287457c9b4b4fc/EditorExtensions/Resources/server/services/srv-sweetjs.js#L57 (we are using `require("xregexp").XRegExp;` there for named captures).

Would be really helpful if sweet.js could return a regular object to make it consumable like:
https://github.com/madskristensen/WebEssentials2013/blob/c82a9a52816bb59fb10833811c287457c9b4b4fc/EditorExtensions/Resources/server/services/srv-less.js#L78-L95

Thanks!

**Comment by disnet** [comment]
I'm mass closing issues due to the release of 1.0 obviating lots of bugs. If you feel this issue is something we still need to address feel free to reopen.

**Comment by am11** [comment]
Lately, there was a next version of WebEssentials released, which phased out the transcompilers as a separate VS extension (WebCompiler, which does not include sweet.js).
However, if I get back to sweet.js in another project, I will definitely investigate and send a PR if necessary.
Thanks.
