### ISSUE TITLE
Allow infix operators to match outside of enclosing delimiters

### ISSUE THREAD

**Issue by kaleb** [mozilla/sweet.js#409]
I ran across this when trying to match the `arguments` keyword when it is called by certain functions. I would like to have it replaced with some other code.

Here's my SO question on it: http://stackoverflow.com/q/26555614/143739

**Comment by disnet** [comment]
I'm mass closing issues due to the release of 1.0 obviating lots of bugs. If you feel this issue is something we still need to address feel free to reopen.
