### ISSUE TITLE
Invalid source maps when using module

### ISSUE THREAD

**Issue by fasterthanlime** [mozilla/sweet.js#411]
Source maps are generated correctly when macros are inline:

  -  **[Gist for macros + usage in the same file](https://gist.github.com/fasterthanlime/205fd2372d8124c56019)**
  - ![screen shot 2014-11-05 at 20 55 24](https://cloud.githubusercontent.com/assets/7998310/4924800/f16b1978-6525-11e4-9c99-10050ca87283.png)

But refer to lines from the wrong file when macros are defined in a module

  - **[Gist for macros in a module + usage in a separate file](https://gist.github.com/fasterthanlime/7fddcf459a7352fdb324)**
  - ![screen shot 2014-11-05 at 20 57 01](https://cloud.githubusercontent.com/assets/7998310/4924821/2aa2e6bc-6526-11e4-98bf-0b7b03f05d6c.png)

As shown by the last screenshot, the source map refers to line 13, which exists in `smacro.sjs`, where the macro is defined, but not in `sstack.sjs`, the code that uses it.

Ideally, the stack trace would look like:

```
sstack.sjs:2 (where `sweet _throw` is used)
sstack.sjs:3 (where problem is called)
```

I'll start digging in the code and try to debug the problem myself, but if anyone in the core sweet.js team can point me in the right direction / knows what's causing this, it would be greatly appreciated.

**Comment by disnet** [comment]
I'm mass closing issues due to the release of 1.0 obviating lots of bugs. If you feel this issue is something we still need to address feel free to reopen.
