### ISSUE TITLE
Can't get "local * in *" block implemented because of bugs

### ISSUE THREAD

**Issue by lilac** [mozilla/sweet.js#412]
I am trying to implement a "local * in *" extension to support (closure) module convention. However, I have tried writing many macros, but still can't get it work. In the process, I felt sweet.js quite unpredicted.

For example, following the "unless" infix operator in the official doc, I implemented the "in" infix operator like the following:
```
macro in {
  rule infix { local $($id:ident = $val:expr) (,) ... | $body:expr } => {
    (function() {
      $(var $id = $val;) ...
      return $body;
    }());
  }
}

local a = 2 in a + 1
```
It outputs
```
local(function () {
    var a$626 = 2;
    return a$626 + 1;
}());
```
Why there is a "local" token in the output? The "unless" operator works well, but this does not, although they look quite similar.

In addition, if I changed the last line to
```
local a = 2, b = 3 in a + b
```
Sweet.js begins complaining
```
SyntaxError: [macro] Macro `in` could not be matched with `a + b ...`
10: local a = 2, b = 3 in a + b
```
Why? Both "a+1" and "a+b" are expressions, why one works but other not?

I have also tried to write a plain rule macro instead of infix operator, but also fail to work it out due to many different strange errors. It really makes me feel sweet.js is so unpredicted and buggy, and those macros which work are just magic.

**Comment by disnet** [comment]
I'm mass closing issues due to the release of 1.0 obviating lots of bugs. If you feel this issue is something we still need to address feel free to reopen.
