### ISSUE TITLE
 Confusing/lacking documentation - please improve to help us newbies... ;)

### ISSUE THREAD

**Issue by kristianmandrup** [mozilla/sweet.js#418]
Dos anyone understand this example!?

"You can name pattern groups and literal groups. Sub-bindings can be referenced by concatenating the group name and binding name. All the syntax matched by the group will be bound to the group name."

Please at least improve the example code so we can see how it can be used in practice :)

what is the "group name" and "binding name"? I assume the group name here is `$binding` since the only concatenated names of are of the form `$binding$id` but that is not very intuitive, perhaps `$id` is the group name but they are concatenated in reverse order in the example?

```js
macro mx {
  rule { ($binding:($id = $val) (,) ...) } => {
    $(var $binding;) ...
    // Or with sub-bindings (equivalent)
    // $(var $binding$id = $binding$val;) ...
  }
}
mx(x = 10, y = 2, z = 3)
```

Apparently, the above binding syntax is shorthand for this: ie. $binding becomes an alias for what is matched inside the following `:()` which can then be used in the output (syntax array) as I understand it

```js
macro m {
  rule { ($($id = $val) (,) ...) } => {
    $(var $id = $val;) ...
  }
}
m(x = 10, y = 2, z = 3)
```

And here the literals example, but I can't find any syntax which matches this rule correctly!?

```js
// example for matching literals in []
macro me {
  rule { $ellipsis:[...] } => {
    ellipsis: $ellipsis 
  }
}
me // error: Macro `me` could not be matched with `...`
me ... // error: Unexpected token ...
```

I just don't get this part...

**Comment by disnet** [comment]
I'm mass closing issues due to the release of 1.0 obviating lots of bugs. If you feel this issue is something we still need to address feel free to reopen.
