### ISSUE TITLE
Dynamic rules

### ISSUE THREAD

**Issue by kristianmandrup** [mozilla/sweet.js#419]
I'm lost trying to create even simple dynamic rules. Been reading the docs for hours...

```js
angular.module('finance2', [])
  .factory('currencyConverter', function() {
    // body
  })
```

How can I turn it into sth like this:

```js
@module Finance2
@type Factory
class CurrencyConverter {
  // body
}
```

Looks like `rule` macros are a no go, since they don't allow dynamic expressions. Which leaves me with case expressions, but they are really hard to understand! Please improve the docs for `case` macros with better/simpler examples and explanations :) 

Feel they docs currently are written for people with a theoretical compiler background...

**Comment by disnet** [comment]
I'm mass closing issues due to the release of 1.0 obviating lots of bugs. If you feel this issue is something we still need to address feel free to reopen.
