### ISSUE TITLE
Please extend the Reader API with more token detection functions

### ISSUE THREAD

**Issue by kristianmandrup** [mozilla/sweet.js#424]
The full list of detection functions `isXXXX` inside parser are not made available in the Reader API

```js
function isIn(el, list)
function isDecimalDigit(ch)
function isHexDigit(ch)
function isOctalDigit(ch)
function isWhiteSpace(ch) 
function isLineTerminator(ch) 
function isIdentifierStart(ch) 
function isIdentifierPart(ch)   
function isFutureReservedWord(id) 
function isStrictModeReservedWord(id)
function isRestrictedWord(id)   
function isKeyword(id)
```

The Reader API only has a select few of those made available, which greatly limits what we can do when parsing tokens... such as detecing whitespace for indentation sensitive languages ;)
or even detecting punctuation (f.ex using `isIn`)

```js
// parser.js
// ReaderAPI

        isIdentifierStart: isIdentifierStart,
        isIdentifierPart: isIdentifierPart,
        isLineTerminator: isLineTerminator,
        isIn: isIn, // missing!!
       // add more token detectors!
```

Cheers :)

**Comment by DavidSouther** [comment]
Poking around looking for a way to make macros capable of handling whitespace (I want indent to be an open brace, and dedent to close the block). These would be very useful to see this land.

**Comment by jlongster** [comment]
Sorry I dropped this! No reason not to include them. I wasn't sure how much to expose at first but it's clear that it would be good to expose a fuller API. I think the only thing to think about it making sure we don't bind ourselves down to a specific version of esprima, and making it easy to upgrade in the future.

**Comment by DavidSouther** [comment]
I think most of these are pretty uncontroversial:
```
function isIn(el, list)
function isDecimalDigit(ch)
function isHexDigit(ch)
function isOctalDigit(ch)
function isWhiteSpace(ch) 
function isLineTerminator(ch) 
function isIdentifierStart(ch) 
function isIdentifierPart(ch)
function isKeyword(id)
```

These might be odd:

```
function isFutureReservedWord(id)  // how far in the future?
function isStrictModeReservedWord(id) // How strict is strict mode? "use-strict" "use-stricter" etc
function isRestrictedWord(id) // Same as above
```

I think they obviously should be included, but need documentation to tie them to specific versions - sweet.js@x.x.x is ES5, sweet.js@x.y.y is ES2015, sweet@y.y.z is ES20Foo with Traceur. (On second thought that's terrible as a proposal, but the idea stands.)

**Comment by kristianmandrup** [comment]
Would be nice with a DSL wrapper on top to make the indentation API easier to work with. 
I think I proposed this in another issue?

**Comment by disnet** [comment]
I'm mass closing issues due to the release of 1.0 obviating lots of bugs. If you feel this issue is something we still need to address feel free to reopen.
