### ISSUE TITLE
Please fix loadMacro helper

### ISSUE THREAD

**Issue by kristianmandrup** [mozilla/sweet.js#425]
I couldn't get `sweet.loadMacro` to work...
Currently I can load my macro like this (taken from jsx-reader), not very pretty.

```js
var helperMacro = sweet.loadNodeModule(__dirname, './macros/hsx-macro.js');
```

Been trying to make it possible to set the macro to be used (by the reader) from the outside, ie. via `process.env` and then defaulting to built-in macro.

```js
var sweet = require('sweet.js');
var defaultMacroPath = './macros/hsx-macro.js';

var macroPath   = process.env.hsxMacroPath || defaultMacroPath;
var helperMacro = sweet.loadMacro(macroPath);
```

However when I try it, I get this error:

```
/Users/kristianmandrup/experiments/frameworks/msx-reader/node_modules/sweet.js/lib/sweet.js:137
                throw err;
                      ^
TypeError: Cannot read property 'env' of undefined
```

Looking at the `loadMacro` function, it looks pretty innocent...

```js
   // sweet js
    var loadedMacros = [];
    // syntax sugar for
    // sweet.loadedMacros.push(sweet.loadNodeModule(process.cwd(), './macros/str'));
    function loadMacro(relative_file) {
        loadedMacros.push(loadNodeModule(process.cwd(), relative_file));
    }
```

Took me a little while to figure out, that the problem is simply that the loaded macro is not returned. Please tweak it to this:

```js
    function loadMacro(relative_file) {
        var mod = loadNodeModule(process.cwd(), relative_file)
        loadedMacros.push(mod);
        return mod;
    }
```

Thanks :)

**Comment by disnet** [comment]
I'm mass closing issues due to the release of 1.0 obviating lots of bugs. If you feel this issue is something we still need to address feel free to reopen.
