### ISSUE TITLE
Support ES6 import statement in compiled files

### ISSUE THREAD

**Issue by gabriel-dehan** [mozilla/sweet.js#426]
Currently, having such a piece of code : 

```javascript
import foo from 'bar';
```
in any file compiled from sjs to js will make the compilation fail with an Escodegen error.
This is a problem that has been issued and fixed here https://github.com/estools/escodegen/issues/180 .
The fix has been part of Escodegen since the 1.4.0 version but sweet.js still relies on the `1.2.x` version.

I have tried bumping the version number in `package.json` but there is an issue with the style code in `sweet.js` files : 

```
/home/xxx/sweet.js/build/lib/sweet.js:47
function (root, factory) {
         ^
Warning: Unexpected token ( Use --force to continue.
```

The issue here is the whitespace between the `function` keyword and the arguments. This whitespace can be found in every function declaration I have looked at and as far as I know is not a really good practice. I can understand it breaks the parsing.

How should this be handled ?

**Comment by disnet** [comment]
I'm mass closing issues due to the release of 1.0 obviating lots of bugs. If you feel this issue is something we still need to address feel free to reopen.
