### ISSUE TITLE
"match" hygiene mismatch inside nested cases

### ISSUE THREAD

**Issue by trxcllnt** [mozilla/sweet.js#430]
If a case macro is created in the body of an outer case macro, the inner cases' `syntax` invocations are renaming their `match` identifiers to an undefined reference. I imagine this is because `syntax` breaks hygiene to capture `match` inside `syntaxCase`.

Here's my example:

```javascript
macroclass inv { pattern { rule { .$fn($args ...) } } }
macro extends_macro {
	case infix { $Macro | _ $Parent { $rules ... } } => {
		var rules = #{ $rules ... }.concat(#{
			case { _ $inv:inv  $[...] ; } => {
				console.clear();
				console.log("breaks after this");
				return #{
					$Parent .$inv$fn($inv$args $[...]);
				}
			}
		});
		return withSyntax($macro_rules ... = rules) #{
			macro $Macro { $macro_rules ... }
		}
	}
}

macro Base {
	rule { .foo(); } => { console.log("foo"); }
}

Impl extends_macro Base {
	case { _ .bar(); } => { return #{ console.log("bar"); } }
}

Impl.foo().bar();
```

http://sweetjs.org/browser/editor.html#macroclass%20inv%20%7B%20pattern%20%7B%20rule%20%7B%20.$fn($args%20...)%20%7D%20%7D%20%7D%0Amacro%20extends_macro%20%7B%0A%09case%20infix%20%7B%20$Macro%20%7C%20_%20$Parent%20%7B%20$rules%20...%20%7D%20%7D%20=%3E%20%7B%0A%09%09var%20rules%20=%20#%7B%20$rules%20...%20%7D.concat(#%7B%0A%09%09%09case%20%7B%20_%20$inv:inv%20%20$%5B...%5D%20;%20%7D%20=%3E%20%7B%0A%09%09%09%09console.clear();%0A%09%09%09%09console.log(%22breaks%20after%20this%22);%0A%09%09%09%09return%20#%7B%0A%09%09%09%09%09$Parent%20.$inv$fn($inv$args%20$%5B...%5D);%0A%09%09%09%09%7D%0A%09%09%09%7D%0A%09%09%7D);%0A%09%09return%20withSyntax($macro_rules%20...%20=%20rules)%20#%7B%0A%09%09%09macro%20$Macro%20%7B%20$macro_rules%20...%20%7D%0A%09%09%7D%0A%09%7D%0A%7D%0A%0Amacro%20Base%20%7B%0A%09rule%20%7B%20.foo();%20%7D%20=%3E%20%7B%20console.log(%22foo%22);%20%7D%0A%7D%0A%0AImpl%20extends_macro%20Base%20%7B%0A%09case%20%7B%20_%20.bar();%20%7D%20=%3E%20%7B%20return%20#%7B%20console.log(%22bar%22);%20%7D%20%7D%0A%7D%0A%0AImpl.foo().bar();

**Comment by disnet** [comment]
I'm mass closing issues due to the release of 1.0 obviating lots of bugs. If you feel this issue is something we still need to address feel free to reopen.
