### ISSUE TITLE
Operator precedence issues

### ISSUE THREAD

**Issue by antlai** [mozilla/sweet.js#432]
In the following example:

    operator (+) 12 left
        {$x, $y} => #{ Sum($x, $y) }
     operator (-) 14
          {$x} => #{ MinusUnary($x) }
     operator (>>) 11 left
          {$x, $y} => #{ Shift($x, $y) }
Applied to:

     var f = 1 >> -2 + 1 ;

I get in release 0.7.2:

    var f = Sum(Shift(1, MinusUnary(2)), 1);

but if I do in the node.js console

    console.log(1 >> -2 +1)

it is printing (1 >> (-2+1))

**Comment by gideonthomas** [comment]
hi @disnet 
I began using sweet.js a few days ago and found it a delight to use!

Thinking about contributing to this project, I was wondering if I could attempt to tackle this bug? If you agree, do you have any suggestions on how I should approach this issue?

**Comment by disnet** [comment]
Awesome! Just a warning, the operator precedence stuff is a bit tricky.

The relevant section of code is [here](https://github.com/mozilla/sweet.js/blob/master/src/expander.js#L1062-L1209) and you might want to refer to the [honu](http://www.cs.utah.edu/plt/publications/gpce12-rf.pdf) paper for details on how enforestation works.

**Comment by gideonthomas** [comment]
Thanks for the guidance! I'll get started on it asap :)

**Comment by gideonthomas** [comment]
I think I'm going to have to take myself off this bug as I am caught up in too many projects right now. Thanks for the support though, and hopefully when I'm a bit more free and if this is still open, I can maybe work on it =)

**Comment by disnet** [comment]
I'm mass closing issues due to the release of 1.0 obviating lots of bugs. If you feel this issue is something we still need to address feel free to reopen.
