### ISSUE TITLE
Using `/` and `'` in macro matching patterns

### ISSUE THREAD

**Issue by iffsid** [mozilla/sweet.js#434]
Would it be possible to enable the use of `/` and `'` as part of macro pattern matches?
I understand that through #290, it ought to be possible to use any symbol within `literal groups`, but they throw up errors when used for these characters/symbols. A workaround for `/` at least, as referenced in #283, appears to be looking at the previous token -- although I'm not sure how that would apply within the pattern-matching part of a macro.

For `/`, trying
~~~
macro scdiv {
  case {_ ($[/] $e ...)} => { return #{ ($e (/) ...) } }
}

scdiv (/ 3 4)
~~~
gives me
~~~
/home/.../sweet.js/lib/parser.js:1898
        throw error;
              ^
Error: Line 21: Invalid regular expression
[... ) } )  ...]
[...snip...]
~~~
and for `'`, trying
~~~
macro scquot {
  case {_ $[']($e ...)} => { return #{[ $e (,) ... ]} }
}

scquot '(1 2 foo bar)
~~~
gives me
~~~
/home/.../sweet.js/lib/parser.js:1898
        throw error;
              ^
Error: Line 27: Unexpected token ILLEGAL
[... ) } )  ...]
[...snip...]
~~~

**Comment by iffsid** [comment]
Any ideas on what would be proper, acceptable ways to solve these issues?
I spent some time trying to hack out a solution to the second issue, but no dice.

**Comment by disnet** [comment]
For your first problem change:

```js
module.exports = {
  readtable: readtable
}
```

to:

```js
module.exports = readtable;
```

**Comment by disnet** [comment]
> [For ', I had to add \\' to the punctuators in the source for readtable in lib/parser.js, otherwise I get the message Error: Line 1: Unexpected token ILLEGAL. I'm fairly sure this constitutes a hack as well and won't be an acceptable change to the source]

Right, overriding `'` and `"` isn't supported in the readtable at the moment. @jlongster do you remember what we'd need to do to get those working properly?

For extending how identifiers are read, I think you could actually use infix macros:

```js
let - = macro {
    case infix { $before:ident | _ $after:ident } => {
	// should check lineNumber/range on $before and $after
	// to make sure there is no space between them

	return [makeIdent(unwrapSyntax(#{$before}[0])  + "_" 
			+ unwrapSyntax(#{$after}[0]), #{$before})];
    }
}

foo-bar
```

Though perhaps the better thing is to have the readtable allow you to override how identifiers are read. Right now the readtable just accepts punctuators but maybe we can make it extend idents too?

**Comment by iffsid** [comment]
>   module.exports = readtable;

Thanks, that worked.

Having the means to extend the readtable to identifiers as well would be great, as very often, the use case of certain punctuators might depend on the context in which they're used. That sort of thing would definitely be easier to handle if extending the readtable to identifiers were possible. (Essentially reader macros, rather than ast-modifying ones.)

It also helps make the handling a bit cleaner when multi-char separators like `->` and `<-` need to be handled, as in the common scheme case of `foo->bar` etc.

**Comment by iffsid** [comment]
In case anyone is interested, the reason I bring up this issue (and others I've brought up previously) is that I'm building a scheme on top of sweetjs called [saccharine scheme](https://github.com/iffsid/saccharine-scheme).
Obviously, it is affected by the base language, so things like early/late -binding, bignums, etc. are not going be available, but modulo such corner cases, I'm hoping that this will enable porting of a large portion of canonical scheme code to being runnable in the browser.
[I'm also hoping that let-syntax type macros will be possible -- scheme macros that desugar into sweetjs macros that desugar scheme syntax into appropriate javascript! :-)]
Comments and suggestions welcome! :-)

**Comment by disnet** [comment]
I'm mass closing issues due to the release of 1.0 obviating lots of bugs. If you feel this issue is something we still need to address feel free to reopen.
