### ISSUE TITLE
Upgrade escope to 2.x

### ISSUE THREAD

**Issue by natefaubion** [mozilla/sweet.js#435]
It should support all of ES6 now.

**Comment by natefaubion** [comment]
@disnet: I can work up a PR for this, would you like me to write it against master or the es6-modules branch?

**Comment by disnet** [comment]
@natefaubion master. I'd like to get at least one more release out before modules land.

**Comment by disnet** [comment]
I'm mass closing issues due to the release of 1.0 obviating lots of bugs. If you feel this issue is something we still need to address feel free to reopen.
