### ISSUE TITLE
Declaring variables in the innermost block?

### ISSUE THREAD

**Issue by fflorent** [mozilla/sweet.js#443]
Is it be possible to declare variables in the innermost block?

I would need it to reimplement the safe-navigation operator (also known as existential operator or `?.`) of [CoffeeScript](http://coffeescript.org/#operators-existential) / Groovy in sweet.js with a good performance.

So turning something like:
````js
var val = func()?.property
````
into pure-JS version like:
````js
var temp = func();
// val takes the value of temp if temp is null or undefined.
var val = (temp != null ? temp.property : temp);
````

But it would be tricky to support these cases:
````js
if (a?.b) {}
switch (a?.b) {
   case c?.d: 
      ...
}
// ES6 arrow-functions with a single instruction... I guess that's an extreme case.
let myFunction = (arg) => arg?.c;
myFunction(a?.b);
/* ... and probably other cases ... */
````

As they should be turned into:
````js
var a_b$1 = a != null ? a.b : a;
if (a_b$1) {}

var a_b$2 = a != null ? a.b : a;
var c_d$1 = c != null ? c.d : c;
switch (a_b$2) {
   case c_d$2: 
      ...
}

let myFunction = (arg) => {
  var arg_c$1 = arg != null ? arg.c : arg;
  return arg_c$1;
}

var a_b$3 = a != null ? a.b : a;
myFunction(a_b$3);
````

FWIW, here is [my code](http://sweetjs.org/browser/editor.html#macroclass%20greedy_prop_chain%20%7B%0A%20%20//%20identifier(arguments...)%0A%20%20pattern%20%7B%0A%20%20%20%20rule%20%7B$chain:($id:ident($args...))%7D%0A%20%20%7D%0A%20%20//%20identifier%5Bkey%5D%0A%20%20pattern%20%7B%0A%20%20%20%20rule%20%7B$chain:($id:ident%5B$key:expr%5D)%7D%0A%20%20%7D%0A%20%20//%20(Default)%20identifier%0A%20%20pattern%20%7B%0A%20%20%20%20rule%20%7B$chain:($id:ident)%7D%0A%20%20%7D%0A%7D%0A%0A//%20Define%20the%20%22?.%22%20operator%0Amacro%20(?.)%20%7B%0A%20%20//%20Support%20syntax%20of%20this%20form:%20a?.b%0A%20%20rule%20infix%20%7B%20$lhs:expr%20%7C%20$rhs:greedy_prop_chain(.)...%20%7D%20=%3E%20%7B%0A%20%20%20%20($lhs%20!=%20null%20?%20$lhs.$rhs$chain(.)...%20:%20$lhs)%0A%20%20%7D%0A%7D%0A%0A//%20Tests%0A%0Aa?.b.c%5Bk.e.y%5D?.d;%0A%0Aa.toSource()?.a;%0A%0A/*%0Afunction%20test%20()%20%7B%0A%20%20//%20Case%201%0A%20%20if%20(a?.b?.c)%20%7B%7D%0A%20%20//%20Case%202%0A%20%20switch%20(a?.b?.c)%20%7B%7D%0A%20%20//%20Case%203%0A%20%20myFunction%20(a?.b?.c);%0A%20%20//%20Case%204%0A%20%20if%20(true)%20val%20=%20a?.b.c%0A%7D*/%0A%0A/*%20I%20would%20have%20liked%20generating%20something%20like:%0A%20%20function%20test()%20%7B%0A%20%20%20%20%20//%20Case%201%0A%09var%20a_b$1%20=%20a%20?%20a.b%20:%20a;%0A%09var%20a_b_c$1%20=%20a_b$1%20?%20a_b$1.c%20:%20a_b$1;%0A%09if%20(a_b_c$1)%20%7B%7D%0A%09%0A%09//%20Case%202%0A%09var%20a_b$2%20=%20a%20?%20a.b%20:%20a;%0A%09var%20a_b_c$2%20=%20a_b$2%20?%20a_b$2.c%20:%20a_b$2;%0A%09switch%20(a_b_c$2)%20%7B%5D%0A%09%0A%09//%20Case%203%0A%09var%20a_b$3%20=%20a%20?%20a.b%20:%20a;%0A%09var%20a_b_c$3%20=%20a_b$3%20?%20a_b$3.c%20:%20a_b$3;%0A%09myFunction(a_b_c$3);%20%0A%09%0A%09//%20Case%204%0A%09if%20(true)%20%7B%0A%09%20%20//%20Pave%20the%20way%20for%20let%20(that%20doesn%27t%20hoist),%20declare%20the%20variable%20inside%20the%20block%20of%20the%20if.%0A%09%20%20var%20a_b$4%20=%20a%20?%20a.b%20:%20a;%0A%09%20%20var%20a_b_c$4%20=%20a_b$4%20?%20a_b$4.c%20:%20a_b$4;%0A%09%20%20val%20=%20a_b_c$4;%0A%09%7D%0A%20%20%7D%0A*/) which uses ternary expressions (so that's not really perfect as it is now).

Florent

**Comment by natefaubion** [comment]
Unfortunately this isn't something we really have an answer for right now. Our macros are purely local, syntactic invocations, so you don't get all the import semantic information you'd need to, say, hoist a definition outside of the head of a switch statement. It's something that's really more suited for an AST transformation. For what we have, you'd really only be able to do it with an IIFE, which is obviously not ideal. It would be great to have an AST phase of some sort to plumb some transforms like this.

**Comment by fflorent** [comment]
Right, is there any means to manipulate the AST in macros?
Otherwise, thanks for the idea of IIFE, it is still more optimized than ternary expressions even if we loose in readability of the result (that's not a big loss since my macros could result in nested ternary expressions, which are not nice). I'll see if I can make something with it.

Florent

**Comment by disnet** [comment]
Sort of. Right now the "AST" manipulation is done via `:expr` and related pattern classes (either by the builtins or building your own via `:invoke`).

But what you really want for this is a (module) global transformation which we can't do at the moment. I think we can do stuff like this once we have modules (an oft repeated phrase of mine lately but I'm getting [close](https://github.com/mozilla/sweet.js/pull/378)!) and localExpand (which we [have](https://github.com/mozilla/sweet.js/pull/310)!) with stop lists (which we don't).

**Comment by fflorent** [comment]
Thanks for the answer. I can wait for this (as I mentioned on my github project, that is experimental).

Florent

**Comment by braco** [comment]
Existential operator in es6 would be so great.

**Comment by fflorent** [comment]
@braco Not in es6 but many TC 39 fellows have it in mind for a future ES version:
https://esdiscuss.org/topic/the-existential-operator

Anyway, that's a bit out of the subject ;).

Florent

**Comment by BrendanEich** [comment]
Still off topic, but existential operator as in CoffeeScript founded with TC39 because not compositional. See https://esdiscuss.org/topic/sept-18-tc39-meeting-notes, look for "Non-starter."

/be

**Comment by disnet** [comment]
I'm mass closing issues due to the release of 1.0 obviating lots of bugs. If you feel this issue is something we still need to address feel free to reopen.
