### ISSUE TITLE
How to use sweet in rhino?

### ISSUE THREAD

**Issue by jckermagoret** [mozilla/sweet.js#444]
Hello,
I use Alfresco which embeds Rhino 1.6. How can I use sweet with rhino?

I don't have AMD or such mechanisms to load js. Is there a (very) minified version of sweet and its libraries?

Thanks a lot,

JC

**Comment by disnet** [comment]
We don't have anything as part of the build process yet. We could probably use webpack to create a single asset right?

**Comment by disnet** [comment]
I'm mass closing issues due to the release of 1.0 obviating lots of bugs. If you feel this issue is something we still need to address feel free to reopen.
