### ISSUE TITLE
Support Hashbang Syntax

### ISSUE THREAD

**Issue by Havvy** [mozilla/sweet.js#446]
Sweet.js chokes on hashbang syntax (`#! /usr/bin/env node` on the first line).

It'd be nice if Sweet.js supported this syntax. Just pass it as is, and don't let it be macroified.

For my own case, I have a workaround, sort of. I can add the hashbang after the fact with a concatenation, at the cost of an off by one error on the sourcemaps.

**Comment by disnet** [comment]
There actually is a PR for this #341. It didn't get cleaned up enough to merge but is probably a good starting point.

**Comment by disnet** [comment]
I'm mass closing issues due to the release of 1.0 obviating lots of bugs. If you feel this issue is something we still need to address feel free to reopen.
