### ISSUE TITLE
Bugs parsing ES6

### ISSUE THREAD

**Issue by buunguyen** [mozilla/sweet.js#457]
Sweet.js throws error for the following 2 cases (valid ES6 code).

Case 1:
```
import * as config from '../module'
```
```
Error: Unexpected token *
[... import * as config from ...]
```

Case 2:
```
export default function () {
  ...
}
```
```
Error: Unexpected token (
[... { } function ( ) { ...]
```

**Comment by marianboda** [comment]
+1

**Comment by disnet** [comment]
I'm mass closing issues due to the release of 1.0 obviating lots of bugs. If you feel this issue is something we still need to address feel free to reopen.
