### ISSUE TITLE
Has issues matching $foo:expr on "var x = ..."

### ISSUE THREAD

**Issue by dfoverdx** [mozilla/sweet.js#459]
I wrote a simple anonymous function c#-like syntax:

	// define c#-style anonymous function syntax
	macro => {
		case infix { () | _ { $body:($line:expr (;) ...) } } => { 
			return #{ function () { $body } };
		}
	}

This will match

	var x = () => { y = 5; };

just fine.  But it will not match

	var x = () => { var y = 5; };

Leaving off the `:expr` doesn't help, either.

**Comment by disnet** [comment]
That's because a variable declaration is not an expression. You probably want:

```js
macro => {
    case infix { () | _ { $body ...} } => { 
        return #{ function () { $body ... } };
    }
}
```

**Comment by dfoverdx** [comment]
That did the trick...

The following also works:

    macro => {
        case infix { () | _ { $body ...} } => { 
            return #{ function () { $body:($line ...) } };
        }
    }

But this doesn't:

    macro => {
        case infix { () | _ { $body ...} } => { 
            return #{ function () { $body:($line (;) ...) } };
        }
    }

Should having a semicolon in there still work?

**Comment by disnet** [comment]
The pattern `$line (;) ...` matches individual tokens separated by `;` so something like `var ; y ; = ; 5` not the entire line.

**Comment by disnet** [comment]
I'm mass closing issues due to the release of 1.0 obviating lots of bugs. If you feel this issue is something we still need to address feel free to reopen.
