### ISSUE TITLE
Sweet.js incorrectly removes the brackets around Immediately-Invoked Function Expressions

### ISSUE THREAD

**Issue by toothbrush7777777** [mozilla/sweet.js#462]
# Example

```javascript
macro class {
    rule { $className:ident { } } => {
        var $className = (function() {
            return;
        })();
    }
}

class ha {

}
```

# Output (incorrect)

```javascript
var ha = function () {
    return;
}();
```

# Correct output

```javascript
var ha = (function () {
    return;
})();
```

[Try it in the Sweet.js Editor](http://sweetjs.org/browser/editor.html#macro%20class%20%7B%0A%20%20%20%20rule%20%7B%0A%20%20%20%20%20%20%20%20$className:ident%20%7B%20%7D%0A%20%20%20%20%7D%20=%3E%20%7B%0A%20%20%20%20%20%20%20var%20$className%20=%20(function()%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20return;%0A%20%20%20%20%20%20%20%20%7D)();%0A%20%20%20%20%7D%0A%7D%0A%0A%0Aclass%20ha%20%7B%0A%0A%7D%0A)

**Comment by disnet** [comment]
That's actually correct output since semantically there's no difference. Escodegen (what we use to generate the JS string after expansion and parsing) strips unnecessary parentheses.

**Comment by toothbrush7777777** [comment]
@disnet  You're totally right. I wasn't paying attention, and it was a separate problem I had that made me think this was the issue.
Sorry for not checking the case I gave you.
