### ISSUE TITLE
Outputing comments using `leadingComments` property fails since v0.7.4

### ISSUE THREAD

**Issue by jwoudenberg** [mozilla/sweet.js#468]
The sweet.js documentation descibes how to output comments using the `leadingComments` property [here](http://sweetjs.org/doc/main/sweet.html#how-do-i-output-comments). However, trying out this exact example using sweet.js v0.7.4 results in an error: `Cannot read property '0' of undefined`.

The error originates [here](https://github.com/mozilla/sweet.js/blob/master/lib/parser.js#L1436). Because the comment we set in the example does not have a `range` property, looking it up fails.

**Comment by disnet** [comment]
Just adding a dummy range seems to make things work out:

```js
macro m {
    case {_ () } => {
        var x = makeValue(42, #{here});
        x.token.leadingComments = [{
            type: "Line",
            value: "hello, world",
            range: [0, 0]
        }];
        return withSyntax ($x = [x]) #{
            $x
        }
    }
}
m()
```

We need a better API for this that figures out the correct range for you.

**Comment by jwoudenberg** [comment]
Thanks, I'll do that. Might be nice to update the documentation though, so others don't run into the same problem.

**Comment by disnet** [comment]
I'll do you one better :)

I just stuck a method onto syntax objects that handles the hack for you:

```js
macro m {
    case {_ () } => {
        var x = makeValue(42, #{here});
        letstx $x = [x.addLineComment(" hello, world")];
        return #{ $x };
    }
}
m()
```

**Comment by jwoudenberg** [comment]
Very nice, thanks!
