### ISSUE TITLE
do-notation block not pattern matching multiple sequential var x = foo blocks

### ISSUE THREAD

**Issue by stevekane** [mozilla/sweet.js#474]
All,

I have been developing a do-notation block macro ala haskell and so far it's been going well.  However, last night I tried to implement multiple sequential var definitions and surprisingly I could not get sweet to pattern match them.  I'm hoping someone here can spot my stupid bug / oversight so I can get this module back on track!  Thanks for all your hard work I adore sweet.js and really want to see it grow into a cornerstone library for javascript.

The issue is with the top case.  The rest of the case match beautifully and work but as shown in the example below, if I try to declare two sequential var x = foo no dice.

Here is the macro definition and link to the source file on github.
```javascript
macro DO {
  //multiple var defs
  case {_ {$name:ident <= $ma:expr var $($k:ident = $v:expr) (var) ... $rest ... }} => {
    return #{
      $ma.bindM(function ($name) {
        $(var $k = $v;) ...
        return DO { $rest ... }
      })
    }
  }

  //single var def
  case {_ {$name:ident <= $ma:expr var $k:ident = $v:expr $rest ... }} => {
    return #{
      $ma.bindM(function ($name) {
        var $k = $v;
        return DO { $rest ... }
      })
    }
  }

  //monadic bindings
  case {_ {$name:ident <= $ma:expr $rest ... }} => {
    return #{
      $ma.bindM(function ($name) {
        return DO { $rest ... }
      })
    }
  }

  //final expressions
  case {_ {$expr:expr}} => {
    return #{$expr}
  }

}
```

Here is an example usage and link to the to source file on github.
https://raw.githubusercontent.com/stevekane/monad-playground/master/quick.js

```javascript
const possibleFullName = DO {
  person <= findWhere(list, props)
  first <= dot('first')(person)
  last <= dot('last')(person)
  var title = 'Mr.'
  var wholeName = title + ' ' + first + ' ' + last
  Maybe.returnM(wholeName)
}
```
Any help here is much appreciated.

Steve

**Comment by disnet** [comment]
Looks like a bug with two repeated patterns following each other (the var decls and the `$rest ...`). Not sure what's causing it.

Here's a possible workaround:

```js
  case {_ {
        $name:ident <= $ma:expr 
        $(var $k:ident = $v:expr)  ... 
        $rest:expr
    }} => {
    return #{
      $ma.bindM(function ($name) {
        $(var $k = $v;) ...
        return DO { $rest }
      })
    }
  }
```

**Comment by natefaubion** [comment]
The issue with repeaters is that they aren't greedy. If there is leftover syntax after the repeater, it always tries to match that first to see if it needs to break out of the repeat. So when you have syntax like `var ... $rest ...` It won't consume all the `var`s first, but instead load the `var`s into `$rest` because it matches everything.

**Comment by stevekane** [comment]
Thanks to both of you for your feedback.  I got pulled into some weekend holiday stuff that pulled my head out of the game for a bit.  I first tried what Tim suggested though based on Nate's response I suspected it wouldn't solve the issue.  It did not.  Given what Nate said and the lack of syntax/semantics in sweet to specify that I want a repeater to be greedy, I decided to try enforcing semi-colons at the end of all lines in DO block.  This as it turns out works well as the parser then scans along until it finds the next semi-colon which causes it to group the repeated pattern together and the rest together as originally intended.

Here is the amended code as it exists at the moment and an example of its use.

```javascript
const possibleFullName = DO {
  person <= findWhere(list, props);
  first <= dot('first')(person);
  last <= dot('last')(person);
  let title = 'Mr.',
      mantra = "whatever",
      wholeName = title + ' ' + first + ' ' + last;
  Maybe.returnM(wholeName);
}

const failedFullName = DO {
  person <= findWhere(list, moreProps);
  first <= dot('first')(person);
  last <= dot('last')(person);
  let wholeName = first + ' ' + last;
  Maybe.returnM(wholeName);
}
```

And the current macro def:

```javascript
macro DO {
  //comma-separated multiple lets
  case {_ {$name:ident <= $ma:expr ; let $($k:ident = $v:expr) (,) ... ; $rest ... }} => {
    return #{
      $ma.bindM(function ($name) {
        $(var $k = $v;) ...
        return DO { $rest ... }
      })
    }
  }

  //monadic bindings
  case {_ {$name:ident <= $ma:expr ; $rest ... }} => {
    return #{
      $ma.bindM(function ($name) {
        return DO { $rest ... }
      })
    }
  }

  //final expressions
  case {_ {$expr:expr ; }} => {
    return #{$expr}
  }
}
```

Any feedback on this solution would be most appreciated.  Also, it might be nice to consider having an optional syntax for specifying the greediness of a repeater pattern.  Maybe ...+ or something to indicate that this repeater will aggressively match until it fails.

Thanks again for your quick and thoughtful responses and hard work on this project.

Steve

**Comment by natefaubion** [comment]
Alternatively, you can get a little clever and write a mini-recursive-decent-parser/expander with pattern classes and identity rules.

```js
macro do_let_binding {
  rule { $name:ident = $rhs:expr }
}

macro do_let_group {
  rule { $let:do_let_binding, $rest:do_let_group }
  rule { $let:do_let_binding }
}

macro do_return {
  rule { return $expr:expr } => { $expr }
}

macro do_term {
  rule { let $group:do_let_group ;... $rest:do_term } => {
    var $group;
    $rest
  }
  rule { $name:ident <- $rhs:expr ;... $rest:do_term } => {
    return $rhs.chain(function($name) {
      $rest
    });
  }
  rule { $expr:do_return ;... $rest:do_term } => {
    return this.pure($expr).chain(function() {
      $rest
    });
  }
  rule { $expr:do_return ;... } => {
    return this.pure($expr);
  }
  rule { $expr:expr ;... $rest:do_term } => {
    return $expr.chain(function() {
      $rest
    });
  }
  rule { $expr:expr ;... } => {
    return $expr
  }
}

let do = macro {
  rule { { $terms:do_term } } => {
    function() { $terms }()
  }
}

var a = do {
  let a = 1
  let b = 2, c = 3
  foo <- doThis(a)
  bar <- doThat(foo)
  return bar + b
}
```
```js
var a = function () {
    var a$2 = 1;
    var b = 2, c = 3;
    return doThis(a$2).chain(function (foo) {
        return doThat(foo).chain(function (bar) {
            return this.pure(bar + b);
        });
    });
}();
```
Semicolons here are completely optional.

**Comment by stevekane** [comment]
@natefaubion  that's beautiful and I was starting to stumble down that path myself last night.  Thanks for taking the time to post this here as it's exactly the kind of iterative improvement I was hoping to make by taking my experimenting public w/ this issue.

**Comment by natefaubion** [comment]
Yeah, it still needs some work. You can for example `return` without having any monad dictionary on hand. I would look at `macroclass` and break apart all the components of the sugar.

**Comment by stevekane** [comment]
@natefaubion To be clear, you are saying that return could be invoked without a 'this' context to define what kind of monad this is?  I had actually favored less sugar in this case and gone with the dumber

```javascript
Maybe.return(x + 1)
```

Is this code snippet taken from a project of yours?  I know I'm by far not the first to create this very macro but I'm curious to know if anyone has actually used such a macro to deliver any non-experimental/demo software?

**Comment by natefaubion** [comment]
No, its just a sketch. Check out https://github.com/fantasyland/fantasy-land and https://github.com/fantasyland/sweet-fantasies/blob/master/src/do.sjs. The latter was written for an old version, and you could probably reimplement it in a saner way.

But yeah, if you want `return` sugar, you have to restrict when you can use it. If you have `do { return foo }` you won't know what monad instance to use. Return-type polymorphism is difficult to do dynamically. You can get around it with some fancy runtime plumbing (http://eighty-twenty.org/2015/01/25/monads-in-dynamically-typed-languages/). For the sugar, you can just restrict when you can use a `return`, ie only after a bind. In the sketch above, it is operating under the assumption that all monadic operations are bound to the current dictionary, so you can fake return-type polymorphism with `this.pure/of/return()`. But you can also do it by `map`ping over the last bound expression. This requires a little more bookkeeping in your macro, but does not require a magic `this`.

**Comment by stevekane** [comment]
Alright I'm pumped now because I took the information @natefaubion provided and combined it with the techniques available in the newer versions of sweet.js to implement a decent chunk of the old sweet-fantasies api.  The current solution supports var/let/const bindings anywhere, an arbitrary mixing of monadic expressions and monadic bindings, and it uses a literal Maybe.returnM(expression) style to minimize the runtime complexity nate mentioned above while still providing a fairly elegant syntax.

Below is the current state of the macro and link to source file and some examples of it being used.

https://github.com/stevekane/monad-playground/blob/master/macros/do-block.js
```javascript
operator (>>=) 15 left 
  { $left, $right } => #{ 
    $left.bindM($right) 
  }

macro variable_type {
  rule { var }
  rule { const }
  rule { let }
}

macro do_let_binding {
  rule { $name:ident = $rhs:expr }
}

macro do_let_group {
  rule { $let:do_let_binding, $rest:do_let_group }
  rule { $let:do_let_binding }
}

macro do_term {
  rule { $variableType:invoke(variable_type) $group:do_let_group ;... $rest:do_term } => {
    (function () { 
      var $group;
      return $rest
    })()
  }

  rule { $name:ident <- $ma:expr ;... $rest:do_term } => {
    $ma >>= (function ($name) { return $rest }) 
  }

  rule { $expr:expr ;... $rest:do_term } => {
    $expr >>= $rest 
  }

  rule { $expr:expr ;... } => {
    $expr
  }
}

macro DO {
  rule { { $terms:do_term } } => {
    (function () { return $terms })()
  }
}

export DO
```

```javascript
const src = `
  DO {
    let x = 5, y = 6
    person <- findWhere(list, props)
    id <- dot('id')(person)
    age <- dot('age')(person)
    Maybe.returnM(id + age + 1)
  }
`

const src2 = `
  DO {
    findWhere(list, props)
    dot('id')
    let bumper = 1
    function (id) { return Maybe.returnM(id + bumper + 1) }
  }
`
```

Thanks for your help @natefaubion and @disnet and feel free to close this "issue" if you would prefer.  Look out for an upcoming blog post about handling async in a more generalized way in the near future using sweet.js!
