### ISSUE TITLE
Macro unit testing best practices

### ISSUE THREAD

**Issue by metaraine** [mozilla/sweet.js#475]
Is there an accepted pattern for writing unit tests for modules? 

It would be nice to compile the macros and run the tests all in memory, but I'm wondering if I have to do a grunt/gulp build process (like [this](https://github.com/natefaubion/lambda-chop/blob/master/Gruntfile.js)).

**Comment by metaraine** [comment]
Didn't need gulp/grunt. Just wrote my mocha test with the macro:

```
it('should compose two functions', function() {
	function add(x,y) { return x+y; }
	function double(x) { return x*2; }
	assert.equal((double +. add)(2,3), 10)
})
```

And added this to my package.json:

```
  "scripts": {
    "test": "sjs --module ./index.js test-src/spec.js > test/spec.js && mocha",
    "clean-test": "rm ./test/*"
  },

```

Still curious if others have a different approach!

**Comment by disnet** [comment]
Yep, that's pretty much what I do.

**Comment by disnet** [comment]
I'm mass closing issues due to the release of 1.0 obviating lots of bugs. If you feel this issue is something we still need to address feel free to reopen.
