### ISSUE TITLE
sweetjs.org expired, on client hold

### ISSUE THREAD

**Issue by AlbertoGP** [mozilla/sweet.js#476]
$ whois sweetjs.org
Domain Name:SWEETJS.ORG
Domain ID: D165783960-LROR
Creation Date: 2012-06-10T06:16:22Z
Updated Date: 2015-06-10T04:49:14Z
Registry Expiry Date: 2015-06-10T06:16:22Z
Sponsoring Registrar:Gandi SAS (R42-LROR)
Sponsoring Registrar IANA ID: 81
WHOIS Server: 
Referral URL: 
Domain Status: clientHold -- http://www.icann.org/epp#clientHold
Domain Status: clientTransferProhibited -- http://www.icann.org/epp#clientTransferProhibited
Registrant ID:DH2266-GANDI
Registrant Name:David Herman
...

**Comment by disnet** [comment]
Looks like @dherman just renewed it.
