### ISSUE TITLE
Simplest browser compile use-case

### ISSUE THREAD

**Issue by iffsid** [mozilla/sweet.js#478]
What would be the _simplest_ setup to have code be macro transformed in the browser?

I found an example [here](http://thecssninja.com/demo/macros/) that was simple and small, but it doesn't cover operator macros and some other kinds of macros, and also only appears to expose `sweet.parse`. The example in the `sweetjs` source on the other hand handles the macros I want, but is quite complex.

What are the minimal set of files and setup one would need if all that is required is to read the text from a particular DOM element (a `textarea`, say), load a macro file that's being served via `sweet.loadMacro` or equivalent, and compile the text with the loaded macros using 

    sweet.compile(text, {modules: loadedmacros})

and get the transformed text.

Apologies if this is something trivial; I'm afraid I don't have much exposure to the `requirejs` side of things.

**Comment by iffsid** [comment]
I think I'm close. Any comments?

As I'm having jekyll setup my webpage, I simply add two scripts: a `main.js` and a `require.js` that I can point at using the `data-main` and `src` fields in my html. I have jekyll serve the sweet.js files from node_modules, so that I can point to the relevant files without needing to copy over much.

My `index.html` and `main.js` are [here](https://gist.github.com/iffsid/cf33a04b9bdb3591c367). The `require.js`, I simply copied over from `sweet.js/browser/scripts`.

However, if I try running the sweet compiler, I get an error saying
```
Uncaught TypeError: Cannot read property 'ArrowFunctionExpression' of undefined
require.define.CodeGenerator.generateFunctionParams	@	escodegen.js:750
require.define.CodeGenerator.generateFunctionBody	@	escodegen.js:784
require.define.CodeGenerator.Expression.FunctionExpression	@	escodegen.js:1671
require.define.CodeGenerator.generateExpression	@	escodegen.js:2018
require.define.CodeGenerator.Statement.ExpressionStatement	@	escodegen.js:1097
require.define.CodeGenerator.generateStatement	@	escodegen.js:2026
require.define.CodeGenerator.Statement.Program	@	escodegen.js:1419
require.define.CodeGenerator.generateStatement	@	escodegen.js:2026
generateInternal	@	escodegen.js:2040
generate	@	escodegen.js:2094
loadMacroDef	@	expander.js:1819
expandToTermTree	@	expander.js:2007
expandTermTreeToFinal	@	expander.js:2265
(anonymous function)	@	expander.js:2335
_.map._.collect	@	underscore.js:98
expand	@	expander.js:2334
expandModule	@	expander.js:2447
ensureStxcaseCtx	@	sweet.js:57
expand$2	@	sweet.js:65
parse	@	sweet.js:123
compile.onclick	@	(index):32
```

It appears to be the case that `escodegen` calls a require from it's node_modules for estraverse, which isn't being fulfilled. However, if I run a simple server within sweet.js' browser directory, then all the scripts load, and I can use sweet's editor just fine without this error.

Anyone have any idea of what would need to be done to fix this?

**Comment by disnet** [comment]
There's some odd escodegen version stuff going on. Are you using escodegen from [here](https://github.com/mozilla/sweet.js/blob/master/browser/scripts/escodegen.js)?

**Comment by disnet** [comment]
I'm mass closing issues due to the release of 1.0 obviating lots of bugs. If you feel this issue is something we still need to address feel free to reopen.
