### ISSUE TITLE
An expression also includes comments?

### ISSUE THREAD

**Issue by fflorent** [mozilla/sweet.js#480]
I am a bit surprised that the expressions also includes comments. To clarify what I mean, here is an example (also the demo is available [here](http://sweetjs.org/browser/editor.html#macro%20foo%20{%0A%20%20rule%20{%20$expr:expr}%20=%3E%20{%0A%20%20%20%20[$expr]%0A%20%20}%0A}%0A%0A//%201.%0Afoo%28bar%29)): 
````javascript
macro foo {
  rule { $expr:expr} => {
    [$expr]
  }
}

// 1.
foo(bar)
````

It results in : 
````javascript
[// 1.
    bar];
````

Which looks a bit weird to me. Is that wanted or is it a bug?

Florent

**Comment by disnet** [comment]
No that was a bug. I think I managed to fix it, had to do with ranges being off on the comment object.

**Comment by fflorent** [comment]
Thanks for the quick reply!

It fixes the above example, indeed. Here is a trickier example that still has the bug (tested with master):
http://ur1.ca/n5pbx

Florent

**Comment by disnet** [comment]
That one is correct maybe?

The comment comes before `document.querySelector...` in both the before and after expansion. Where else should it go?

Maybe I'm missing something.

**Comment by fflorent** [comment]
> The comment comes before `document.querySelector...` in both the before and after expansion.

Sorry, I don't understand what you mean (especially with "the before and after expansion")

Florent

**Comment by fflorent** [comment]
As told on IRC, the comment is bound to the first token. I have to move the comment (leadingComments property) where I want (to the var statement).

Florent
