### ISSUE TITLE
trailing comments are stripped out

### ISSUE THREAD

**Issue by fflorent** [mozilla/sweet.js#481]
Taking this example:

````javascript
macro foo {
  rule { $expr:expr} => {
    [$expr]
  }
}

// 1.
foo(bar)
// 2.
````

results in:
````
// 1.
[bar];
````

I would expect to have the second comment too:
````
// 1.
[bar];
// 2.
````

**Comment by disnet** [comment]
I'm mass closing issues due to the release of 1.0 obviating lots of bugs. If you feel this issue is something we still need to address feel free to reopen.
