### ISSUE TITLE
Suggestion: leave invalid productions as-is

### ISSUE THREAD

**Issue by impinball** [mozilla/sweet.js#483]
This would allow this to be generalized quite a bit, being less JavaScript-specific. As an example:

```ts
macro id {
  rule { $foo } => { $foo }
}

enum Foo {
  bar,
}

id enum Foo {
  bar,
}
```

This could simply be printed as this:

```ts
enum Foo {
  bar,
}

enum Foo {
  bar,
}
```

Or, another example:

```
macro apply {
  rule { $bar $baz } => { $bar $baz 1 }
}

apply foo bar baz
```

This could be printed as this:

```
foo bar baz 1
```

Would this be at all possible to do?

**Comment by vendethiel** [comment]
how do you expand macros from generated code?

**Comment by impinball** [comment]
@vendethiel If you're talking about recursive macros, it should still be possible.

Keep in mind, my hopes aren't too high for this to even work. (syntax validation on input would be significantly more complex.) Actually, I'm just going with my instincts and closing this bug.

**Comment by disnet** [comment]
Yeah this would be nice to have but I think it raises too many problems to be worth attempting right now.

**Comment by impinball** [comment]
The idea has practical issues in how to implement, too. Ones I never really
thought of initially. Like, how are you supposed to figure out legitimate
syntax errors and print them out meaningfully? Or know when to stop parsing
a macro definition.
