### ISSUE TITLE
proposed change in macro precedence

### ISSUE THREAD

**Issue by disnet** [mozilla/sweet.js#484]
So, macros have a bug (sort of) when it comes to precedence. Observe:

```js
macro m {
    rule {} => {
        4 + 5
    }
}
m * 6
// what you might expect to happen
// (4 + 5) * 6 === 54
// what actually happens
// 4 + (5 * 6) === 34
```

One (bad) solution to this is to just tell macro authors to just wrap their output in parens if they care about precedence.

Better is to do this automatically in the expander. I think we can just run the enforester on the macro invocation result until it gets an expression term. Basically this would implicitly parenthesize the macro output.  

The maybe-problem with this approach is that other macros in the output of a macro would be limited to match only the syntax inside the implicit parens:

```js
macro n {
    rule { $rest ... } => {
        // do something with $rest ...
    }
}
macro m {
    rule {} => {
        4 + 5 - n
    }
}
m * 6 // n does *not* match `* 6`
```

I *think* this is ok but what do other people think?

**Comment by vendethiel** [comment]
Requiring macro authors to add parentheses remind me of C macros, so I'd vote against that

**Comment by disnet** [comment]
I'm mass closing issues due to the release of 1.0 obviating lots of bugs. If you feel this issue is something we still need to address feel free to reopen.
