### ISSUE TITLE
Is it possible to replace a function, not calls to it?

### ISSUE THREAD

**Issue by retorquere** [mozilla/sweet.js#487]
I'm using xregexp in an environment where modifying prototypes is verboten, so I'd like to turn

```
function setNatives(on) {
        RegExp.prototype.exec = (on ? fixed : nativ).exec;
        RegExp.prototype.test = (on ? fixed : nativ).test;
        String.prototype.match = (on ? fixed : nativ).match;
        String.prototype.replace = (on ? fixed : nativ).replace;
        String.prototype.split = (on ? fixed : nativ).split;
        features.natives = on;
    }
```

into
```
function setNatives(on) { throw new Error("Modifying prototypes not allowed"); }
```

I currently do this using a ruby script, but I was wondering whether it'd be possible to do this using sweet.js

**Comment by disnet** [comment]
Are you just worried about the builtins (`String`, `Array`, etc.)? If so you could just write macro for each `String`, `Array`... with a pattern like `. prototype . $ident = $val:expr`.

If you want it for custom objects maybe you could write a `=` infix macro. Something like:

```js
let = = macro {
  rule infix { $name . prototype . $prop | $val:expr } => {
    throw "error" 
  }
  rule {  $rest ... } => {
    = $rest ...
  }
}
```

**Comment by retorquere** [comment]
It's a little different still -- the resulting code will have to pass Mozilla's somewhat-arbitrary extension code validator -- assignments to X.prototype.Y are OK *unless* they're for builtins, in which case they do not just have to be not-executed, they have to be not-present.

Could the first of your examples be used to change each of the `RegExp.prototype.X = ...` into `throw new Error("Don't assign to RegExp.prototype.X")`? Or is that better handled with the second approach?

**Comment by retorquere** [comment]
@disnet: could I use the first form you describe to change `Date.newmethod = ...` to `DateParser.newmethod = ...`? (and if so, could you give me a sample -- I haven't been able to construct anything that works yet).

**Comment by retorquere** [comment]
Or at least, the following throws an error when I run it over my JS code:

```
macro Date {
  rule { . $attrib = $val:expr} => { DateParser.$attrib = $val }
}
```

(granted, the JS code is fairly dense -- it is a browseryfied version of the datejs library, perhaps it's just esprima throwing an error -- but it'd be good to know if the above is in principle correct)

**Comment by disnet** [comment]
Your `Date` macro seems to work with the simple examples I throw at it.

**Comment by retorquere** [comment]
The authors of the original library are going to remove the methods I tried to sweeten out. Thanks for the help people.

**Comment by chocolateboy** [comment]
@retorquere: I'm also using XRegExp in a Firefox addon I'm working on (there's [another issue](https://github.com/slevithan/xregexp/pull/113) which prevents it working in Firefox). I wasn't aware of this restriction, so I appreciate the heads-up.

I don't think this particular fix is in the wheelhouse of sweet.js. I think the best general solution for this kind of code surgery is [grasp](http://www.graspjs.com/).

**Comment by retorquere** [comment]
Thanks for the tip, I'll look into that.

It's not that such calls are forbidden in Firefox extensions, it's just
that they trigger manual review. If you're OK with multi-week barriers to
release while an overworked volunteer checks your code against Mozilla's
security theater it doesn't affect you :/ (it's subtle, but you may have
noticed I have an opinion on the matter)

**Comment by chocolateboy** [comment]
<sub>(I share your opinion :-)</sub>

**Comment by disnet** [comment]
I'm mass closing issues due to the release of 1.0 obviating lots of bugs. If you feel this issue is something we still need to address feel free to reopen.
