### ISSUE TITLE
Local hygienic variables

### ISSUE THREAD

**Issue by polkovnikov-ph** [mozilla/sweet.js#488]
Consider this example

	macro test {
		case {
			$top {
				$body ...
			}
		} => {
			return #{
				function (ident) {
					$body ...
				}
			};
		}
	}

	var ident;
	var a = test {
		var b = foo;
		var ident;
		var c = foo;
	};

What technique should be applied to generate the following result (i.e. rename `foo` to the locally available variable)?

	var ident;
	var a = function (ident$2) {
		var b = ident$2;
		var ident$3;
		var c = ident$2;
	};

I've tried
 - creating local `macro foo` inside `#{...}` clause, but it results in a global rewrite.
 - putting `macro foo` outside `#{...}` and calling `localExpand` in the hope that macro will be local to case macro replacement clause.

**Comment by disnet** [comment]
I think what you can do is bend the `foo` in `macro foo` and place that inside the function expr (which keeps it locally scoped):

```js
macro test {
    case {
        $top {
            $body ...
        }
    } => {
        letstx $foo = [makeIdent("foo", #{$top})];
        return #{
            function (ident) {
                macro $foo {
                    rule {} => { ident }
                }
                $body ...
            }
        };
    }
}
```

Does that do what you are asking for?

**Comment by disnet** [comment]
I'm mass closing issues due to the release of 1.0 obviating lots of bugs. If you feel this issue is something we still need to address feel free to reopen.
