### ISSUE TITLE
Problem with babel-integration

### ISSUE THREAD

**Issue by fab1an** [mozilla/sweet.js#489]
I have this macro:
````

macro makeStr {
  case {_ $x:ident} => {
    return [makeValue(unwrapSyntax(#{$x}).toString(), #{$x})]
  }
}

macro $ {
    rule infix { | .$map:ident.$param:invoke(makeStr) (.) ...}  => {
        deepGet($map, [$param (,) ...])
    }
}

export $
````

and load it via babel and webpack (first babel, then sweetjs). The translation works like this:

`$.a.b.c   =>    deepGet(a,'b','c')`

the problem is that the deepGet function that I define right before using my macro get's renamed, so the expanded macro doesn't find it. This is the case with "readable-names" as well.

**Comment by disnet** [comment]
Where do you define `deepGet`? If it's in the same file than it should just work.

**Comment by fab1an** [comment]
3 lines above. It get's renamed as deepGet$2 or something, but the deepGet in the macro isn't.

**Comment by disnet** [comment]
Ah, you have something like:

```js
function deepGet() { /* ... */ } // renamed to deepGet$2
$.a.b.c // deepGet(a, 'b', 'c')
```

Eventually (with proper module support) this will "just work" but until then you can get around this by bending hygiene on the `$` macro. Something like:

```js
macro $ {
    case { $mname .$map:ident.$param:invoke(makeStr) (.) ...}  => {
        letstx $fnName = [makeIdent("deepGet", #{$mname})];
        return #{$fnName($map, [$param (,) ...])};
    }
}
```

**Comment by fab1an** [comment]
That works, thank you. Should I keep this issue open?

**Comment by kress95** [comment]
Sorry for asking here, but you're piping the output of babel to sweetjs?
How babel parses sweetjs syntax without throwing errors?
I wanted to try it here too :)

**Comment by disnet** [comment]
Babel can't parse sweet.js syntax without throwing errors. @fab1an was defining his macros in an external file that wasn't being passed to babel. The macro *uses* of `$` were in a file that babel parsed but that worked because `$` was valid ES6.
