### ISSUE TITLE
C preprocessor like macros (without hygiene)

### ISSUE THREAD

**Issue by myocytebd** [mozilla/sweet.js#490]
How to disable hygiene?
"Hygiene Part 2 (Reference)" can be undesired.
Example:
```
macro empty { rule { ($x ...) } => {} }

function wrapper() {
var empty = require('empty');
function fn() {
  empty(arg); //How to expand this site?
}
}
```

**Comment by disnet** [comment]
Sorry, I'm not sure what you are asking. In your example the `var empty` binding overrides the `macro empty` binding from earlier. This isn't hygiene, just normal scoping.

**Comment by myocytebd** [comment]
I want to expand macro like C/C++ preprocessors, which does honor language scoping.
Is there a way to define a macro cpp-like, without bound to scoping?

**Comment by disnet** [comment]
No. Macro bindings can always be shadowed.

- Tim
