### ISSUE TITLE
Problem generating ES6 syntax

### ISSUE THREAD

**Issue by jmaher409** [mozilla/sweet.js#492]
This is somewhat related to some other issues I saw but seems slightly different as at pertains to using sweetjs to generate es6 code as opposed to parsing it. I'm new to sweetjs so please forgive if I'm just not seeing how to make this work. I'm trying to write a macro that ends up generating some values to be exported from an es6 module. Here is a very simplified macro that shows the problem I am running into.

```
macro exportMaker {
    case {
        _ $ident
    } => {
      
        return #{
            $[export] $ident           
        };
        
    }
}

exportMaker m
```

I would expect the $[...] syntax to allow me to just generate the export keyword but it doesn't seem to be working since nothing is generated. Any help would be much appreciated.

**Comment by disnet** [comment]
Yep, this currently won't work. Full ES6 support (and lot's more) is being worked on (https://github.com/mozilla/sweet.js/pull/485) but it's not ready yet.

**Comment by disnet** [comment]
I'm mass closing issues due to the release of 1.0 obviating lots of bugs. If you feel this issue is something we still need to address feel free to reopen.
