### ISSUE TITLE
Manually created delimiters fail to properly infer the range from child-delimiters

### ISSUE THREAD

**Issue by bopjesvla** [mozilla/sweet.js#493]
This readtable:

    {
	  "-": (chr, reader) => {
	  	reader.readPunctuator();
  		return reader.makeDelimiter("{}", [reader.makeDelimiter("{}", [reader.readToken()])])
	  },
	  "+": (chr, reader) => {
	  	reader.readPunctuator();
  		return reader.makeDelimiter("{}", [reader.readToken()])
	  }
    }

applied to this program:

    -5

results in the unparsable:

	[ { token:
	     { type: 7,
	       value: '{',
	       range: undefined,
	       sm_range: undefined,
	       lineNumber: undefined,
	       sm_lineNumber: undefined,
	       lineStart: undefined,
	       sm_lineStart: undefined },
	    context: Def { defctx: [], context: [Object], instNum: 130026 },
	    deferredContext: null },
	  { token:
	     { type: 7,
	       value: '{',
	       range: [Object],
	       sm_range: [Object],
	       lineNumber: 1,
	       sm_lineNumber: 1,
	       lineStart: 0,
	       sm_lineStart: 0 },
	    context: Def { defctx: [], context: [Object], instNum: 130029 },
	    deferredContext: null },
	  { token:
	     { type: 6,
	       value: 5,
	       lineNumber: 1,
	       lineStart: 0,
	       range: [Object],
	       sm_lineNumber: 1,
	       sm_lineStart: 0,
	       sm_range: [Object] },
	    context: Def { defctx: [], context: [Object], instNum: 130030 },
	    deferredContext: null },
	  { token:
	     { type: 7,
	       value: '}',
	       range: [Object],
	       sm_range: [Object],
	       lineNumber: 1,
	       sm_lineNumber: 1,
	       lineStart: 0,
	       sm_lineStart: 0 },
	    context: Def { defctx: [], context: [Object], instNum: 130029 },
	    deferredContext: null },
	  { token:
	     { type: 7,
	       value: '}',
	       range: undefined,
	       sm_range: undefined,
	       lineNumber: undefined,
	       sm_lineNumber: undefined,
	       lineStart: undefined,
	       sm_lineStart: undefined },
	    context: Def { defctx: [], context: [Object], instNum: 130026 },
	    deferredContext: null },
	  { token:
	     { type: 2,
	       value: '',
	       lineNumber: undefined,
	       lineStart: undefined,
	       range: [Object],
	       sm_lineNumber: undefined,
	       sm_lineStart: undefined,
	       sm_range: [Object] },
	    context: Def { defctx: [], context: [Object], instNum: 130027 },
	    deferredContext: null } ]

`+{5}` results in something similar.

A nested delimiter padded with other tokens, on the other hand, can be parsed just fine, although the trailing `''` token remains:

     return reader.makeDelimiter("{}", [reader.makeNumericLiteral(5), reader.makeDelimiter("{}", [
			reader.readToken()]), reader.makeNumericLiteral(5)])

**Comment by disnet** [comment]
I'm mass closing issues due to the release of 1.0 obviating lots of bugs. If you feel this issue is something we still need to address feel free to reopen.
