### ISSUE TITLE
:expr matches don't play nice with ASI

### ISSUE THREAD

**Issue by bopjesvla** [mozilla/sweet.js#494]
let identity = macro {
    	rule { $l:expr } => { $l }
    }
    a
    identity b

outputs

    a(b);

**Comment by disnet** [comment]
Yep, known problem. I'm working on getting rid of this behavior.

**Comment by disnet** [comment]
I'm mass closing issues due to the release of 1.0 obviating lots of bugs. If you feel this issue is something we still need to address feel free to reopen.
