### ISSUE TITLE
Can't create a haskell like macro

### ISSUE THREAD

**Issue by avikalpa** [mozilla/sweet.js#495]
I want to create a macro like this
```javascript
var diffLength =
    | index1 === 0 then xPos[index1]
    | index1 === 2 then (xPos[index1] - xPos[index1 - 1]) * focusFactor
    | otherwise xPos[index1] - xPos[index1 - 1]
```
which should expand like :
```javascript
var diffLength = 
   index1 === 0 ? xPos[index1] :
   index1 === 2 ? (xPos[index1] - xPos[index1 - 1]) * focusFactor : 
   xPos[index1] - xPos[index1 - 1];
```
SweetJS code :
```javascript
macro |{
    rule { 
      $cond:expr then $check:expr $($guard:(|) $restCond:expr then $restCheck:expr) ... $lastGuard:(|) otherwise $lastCheck:expr
    } => { 
      ( $cond ? $check : $($restCond ? $restCheck :) ... $lastCheck )
    }
}
```
which works only if I change $guards:(h) and $lastGuard:(h) insteed of  $guards:(|) and $lastGuard:(|) and actual code like
```javascript
var diffLength =
    | index1 === 0 then xPos[index1]
    h index1 === 2 then (xPos[index1] - xPos[index1 - 1]) * focusFactor
    h otherwise xPos[index1] - xPos[index1 - 1]
```
Reason is I am unable to stop sweetjs to parse the adjacent "|"(pipe) delimiters.
Can anyone suggest how can I do it?

**Comment by disnet** [comment]
You can try something like this:

```js
macro guardcheck {
    rule { | otherwise $body:expr } => {
        $body
    }
    rule { | $guard:expr then $body:expr, $rest ... } => {
        $guard ? $body : guardcheck $rest ... 
    }
}
let var = macro {
    rule { $ident = $check:guardcheck } => {
        var $ident  = $check
    }
}

var diffLength =
    | index1 === 0 then xPos[index1],
    | index1 === 2 then (xPos[index1] - xPos[index1 - 1]) * focusFactor,
    | otherwise xPos[index1] - xPos[index1 - 1]
```

Note that since `|` is bitwise OR you need something like a `,` to mark the end of each line. Otherwise the `:expr` class will match `xPos[index1] | index1 === 2` as an expression.

**Comment by avikalpa** [comment]
Thanks a lot. I have spent the entire day trying to figure out how to do it. I would never have figured that out by reading the documentation. You guys should provide the docs for such patterns as using a macro inside a macro.

 Another issue
I want to create a macro like this
```javascript
quickSort =  function(xs){
  return smallerSorted + pivot + biggerSorted
    where smallerSorted = quickSort('ko')
          biggerSorted = quickSort('mo')
          pivot = xs[xs.length/2].
};
```
which should expand like :
```javascript
quickSort = function (xs) {
    smallerSorted = quickSort('ko');
    biggerSorted = quickSort('mo');
    pivot = xs[xs.length / 2];
    return smallerSorted + pivot + biggerSorted;
};
```
SweetJS code :
```javascript
macro where{
  rule infix { return $caller:expr | $body ... .} => {
    $body
    ...
    ;
    return $caller;
  }
}
```
This actually expands to 
```javascript
quickSort = function (xs) {
    return smallerSorted = quickSort('ko');
    biggerSorted = quickSort('mo');
    pivot = xs[xs.length / 2];
    return smallerSorted + pivot + biggerSorted;
};
```

It only works only if I change return to something else say &return and actual code like
```javascript
quickSort =  function(xs){
  &return smallerSorted + pivot + biggerSorted
    where smallerSorted = quickSort('ko')
          biggerSorted = quickSort('mo')
          pivot = xs[xs.length/2].
};
```
Reason : I am unable to use keywords as syntax objects and change their position.

**Comment by disnet** [comment]
This is happening because the `return` keyword creates an implicit delimiter that the `infix` macro cannot match outside of. 

This is not well documented at the moment because the design of `infix` is in flux. They have some odd edge cases and interact in strange ways with existing syntax forms. Once we nail it down we will communicate this better but in the meantime I'd recommend you try and avoid using infix macros if possible. Actually, even after we nail things down `infix` should be thought of as the macro definition form of last resort.

It's much simpler to just use a standard macro for `return`:

```js
let return = macro {
  rule { $caller:expr where $($ident = $init:expr) ... .} => {
    $(var $ident = $init;) ...
    return $caller;
  }
}
quickSort =  function(xs){
  return smallerSorted + pivot + biggerSorted
    where smallerSorted = quickSort('ko')
          biggerSorted = quickSort('mo')
          pivot = xs[xs.length/2].
};
```

**Comment by avikalpa** [comment]
Thanks I will keep that in mind when using ```infix``` for the time being. How to tell sweetjs that if syntax of a macro doesn't match then ignore that case instead of stopping and throwing an error ?
Consider the case below :
```javascript
let return = macro {
  rule { $caller:expr where $($ident = $init:expr) ... .} => {
    $(const $ident = $init;) ...
    return $caller;
  }
}
let where = macro {
    rule infix { $callerId = $callerValue:expr | $($id = $value:expr) ... . } => {
    $(const $id = $value;) ...
    const $callerId = $callerValue;
    }
}

quickSort =  function(xs){
  return smallerSorted + pivot + biggerSorted
    where smallerSorted = quickSort('ko')
          biggerSorted = quickSort('mo')
          pivot = xs[xs.length/2].
};

yoSort = smallerSorted + pivot + biggerSorted
  where smallerSorted = quickSort('koq')
        biggerSorted = quickSort('moq')
        pivot = xs[xs.length/2].
```
This code shows throws an error like
```
SyntaxError: [macro] Macro `where` could not be matched with `smallerSorted = quickSort () biggerSorted...`
16:     where smallerSorted = quickSort('ko')
        ^
```
Removing the ```quicksort``` function goes fine.

**Comment by disnet** [comment]
> How to tell sweetjs that if syntax of a macro doesn't match then ignore that case instead of stopping and throwing an error ?

You do this by having multiple rules in a macro definition. Each rule will be attempted top-down.

But thinking about it a bit more, I think in this case the best approach is to use a single `infix` macro:

```js
let where = macro {
    rule infix {
        $callerValue:expr | $($id = $value:expr) ... .
    } => {
        (function() {
            $(const $id = $value;) ...
            return $callerValue;
        })();
    }
}
```

Infix macros that match a single term in front of them like this one are part of the subset of well-behaved infix macros (ie. there shouldn't be any strange interaction with other syntax forms).

> Is it possible in sweetJS to make compile-time execution of a macro like [1..10] to [1,2,3,4,5,6,7,8,9,10]

You can but the lexical structure of JavaScript makes this one surprisingly tricky. The source `1..10` will actually lex into two tokens `1.` (ie `1` with a decimal place) and `.10`. There are a couple of approaches you could take. One is to make a `..` macro and just require a space between the tokens and the macro. So `[1 .. 10]` would work but `[1..10]` would not. Another approach would be to make a `.` macro and not force spacing so that the syntax would look like `[1...10]`:

```js
macro (.) {
    case infix {_ $start | $end } => {
        // $start will contain the token 1.
        // $end will contain the token .2
    }
}
[1...10]
```

Personally, I'd go with an entirely different syntax to avoid the lexer interactions with `.`. Maybe `[1 to 10]`?

**Comment by avikalpa** [comment]
Your solution seems not to work :
```javascript
let where = macro {
    rule infix {
        $callerValue:expr | $($id = $value:expr) ... .
    } => {
        (function() {
            $(const $id = $value;) ...
            return $callerValue;
        })();
    }
}
let return = macro {
  rule { $caller:expr where $($ident = $init:expr) ... .} => {
    $(const $ident = $init;) ...
    return $caller;
  }
}

const yoSort = smallerSorted + pivot + biggerSorted
  where smallerSorted = quickSort('koq')
        biggerSorted = quickSort('moq')
        pivot = xs[xs.length/2].
        
const quickSort =  function(xs){
  return smallerSorted + pivot + biggerSorted
    where smallerSorted = quickSort('ko')
          biggerSorted = quickSort('mo')
          pivot = xs[xs.length/2].
};
```
yeilds error as 
```
SyntaxError: [macro] Macro `const` could not be matched with `yoSort = smallerSorted + pivot...`
43: const yoSort = smallerSorted + pivot + biggerSorted
    ^
```
And if I change to ```[1 to 10]``` how could I make it expand to ```[1,2,3,4,5,6,7,8,9,10]``` in compile time NOT as a runtime loop?

**Comment by disnet** [comment]
Ha! Tricky...the ending `.` is confusing things because `xs[xs.length/2].const` is totally a valid expression even though it's separated by a new line. Try dropping the `.` and separating each assignment with a comma:

```js
let where = macro {
    rule infix {
        $callerValue:expr | $($id = $value:expr) (,) ... 
    } => {
        (function() {
            $(const $id = $value;) ...
            return $callerValue;
        })();
    }
}

const yoSort = smallerSorted + pivot + biggerSorted
  where smallerSorted = quickSort('koq'),
        biggerSorted = quickSort('moq'),
        pivot = xs[xs.length/2];

const quickSort =  function(xs){
  return smallerSorted + pivot + biggerSorted
    where smallerSorted = quickSort('ko'),
          biggerSorted = quickSort('mo'),
          pivot = xs[xs.length/2]
};
```

**Comment by disnet** [comment]
For `[1 to 10]` you'll need to use a [case macro](http://sweetjs.org/doc/main/sweet.html#case-macros). That will allow you to inspect the value of the beginning and ending numeric literals and then generate the appropriate syntax objects.

**Comment by avikalpa** [comment]
I really don't understand what I'm doing wrong :
```javascript
let m = macro {
 case { _ $start $stop} => { 
   var a = (function () {
     var b = [];
     var index =0;
     for (var i = #{$start}; i < #{$stop}; i++){
       b[index] = i;
       index++;
     }
     return b;
   })();
   return #{ [a] }
 }
}

q = m 1 5;
```
This generates ```q = [a$5540];```

**Comment by disnet** [comment]
Our documentation on `case` macros leaves a lot to be desired. A gentle tutorial has been on my todo list for a while.

Here's an annotated example of how you can do it though:

```js
macro to {
    case infix {  $start:lit | _  $end:lit } => {
        // unwrap the syntax objects matched by $start and
        // $end into their respective numbers
        var startValue = unwrapSyntax(#{$start});
        var endValue = unwrapSyntax(#{$end});
        
        // needed for hygiene
        var ctx = #{$start};
        
        // make an array of syntax objects for each number
        // in the range
        var resultNumbers = []; 
        for (var i = startValue; i <= endValue; i++) {
            // `makeValue` creates a syntax object the represents
            // the literal given as the first argument. For example,
            // makeValue(24, ctx) makes the syntax object representing
            // the numeric literal `24`
            resultNumbers.push(makeValue(i, ctx));
        }
        
        // bind each numeric literal to the pattern `$nums` which
        // can now be used inside of templates
        letstx $nums ... = resultNumbers; 
        return #{$nums (,) ...};
    }
}

[1 to 10]
```

**Comment by avikalpa** [comment]
Thanks.
Could you tell me what does this error mean :
```
Error: ASSERT: must have a least one non-scalar in repeat
```
code:
```javascript
let guardcheck = macro {
    rule { $($guard:(|) $cond:expr then $val:expr) (,) ... $guard otherwise $last:expr,
    } => {
        (function(){            
               return $($cond ? $val :) ... $last ;            
        })()
    } 
    
    rule { $($guard:(|) $cond:expr then $val:expr) (,) ... // Add comma here // Error is caused here `Why?`
    } => {
        (function(){            
               return $($cond ? $val :) ... undefined ;            
        })()
    }

}
let const = macro {
    rule { $ident = $check:guardcheck } => {
        const $ident  = $check
    }
    rule { $ident = $check:expr} => {
        const $ident  = $check
    }
}
let where = macro {
    rule infix {
        $callerValue:expr | $($id = $value:expr) (,) ...
    } => {
        (function() {
            $(const $id = $value;) ...
            return $callerValue;
        })()
    }
}

const abc =
    | x < 3 then 6,
    | x == 5 then 4, // Add comma here
  //  | otherwise 5, // Works OK
    where x = 2;
```
**Many a time I am encountered with this error while writing patterns inside macros.**
Is it that ```...``` must always be delimited by a ```literal``` ?
If thats so, in the docs there's an example as
```javascript
macro m {
    rule { $x $($p:(+) $x) ... }
      => { $x * (1 $($p 1) ...) }
}
m 23 + 23 + 23   // expands to 23 * (1 + 1 + 1);
m 23 + 23 + 42   // expands to 23 * (1 + 1) + 42;
```
which has nothing after ```...```

**Comment by disnet** [comment]
So normally that error means you are attempting to use `...` incorrectly. For example:

```js
macro m {
    rule { $x } => {
        [$x (,) ...]
    }
}
```

would throw that error because the pattern `$x` only matched a single token but the template is using `$x` as if it matched a sequence of tokens.

However, in your case I'm having a little trouble tracking down exactly why it is being triggered. It looks like it has something to do with the interaction of the `const` macro being used in the `where` macro's template.

I think you can fix the problem by avoiding the interaction and just declaring the `const` macro *after* the `where` macro. That should work just fine for you since `where` doesn't need the extra capabilities of `const`.
