### ISSUE TITLE
Conditional Token Variables

### ISSUE THREAD

**Issue by jasuperior** [mozilla/sweet.js#497]
I just thought of this today, and thought it would be a good idea to pass it to you guys, since it would make some of my source code considerably smaller, and i think could work in lots of use cases for tons of other users. 

Okay, here's the scenario, you want to make a macro which has a token variable which is not required for the rule to match:
```javascript
//macro.sjs

macro x {
    rule { $id:ident } => { fn.call($id) }
    rule {$num:lit $id:ident } => { fn.call($id, $num) }
}
```
```javascript
//app.js
x person
//compiles to:
//fn.call(person)
x 56 person
//compiles to : fn.call(person, 56)
x 56
//ERROR
```

in cases like this, where the macro ```x``` has dual functionality, i was forced to seperate, what is essentially the same rule, into 2 rules. It could be simplified easily by adding the ability to make conditional token vars. you could denote it with something like   ```$$``` or  ```$$( $var )``` but essentially, it would mean that that particular variable can and cannot be there, in either case, match. 

so macro.sjs could be rewritten
```
//macro.sjs

macro x {
    case { _ $$num $id:ident } => { 
        if( itExists(#{ $$num  })  ) {
            return #{ fn.call($id, $num) }
        }
        else {
            return #{ fn.call($id) }
        }
    }
}
```

we would need a couple helper functions for conditional checks, but essentially, methods such as ```itExists``` and others can just check the token provided for the expected values. 

Just an idea. what do you guys think?

**Comment by disnet** [comment]
I think you can everything you are asking for already via [`:invoke`](http://sweetjs.org/doc/main/sweet.html#the-invoke-pattern-class):


```js
macro opt_lit {
    rule { $num:lit } => { $num }
    rule { } => {}
}

macro x {
    case {_ $num:opt_lit $id:ident } => { 
        var opt = #{$num};
        if (opt.length === 0) {
            return #{fn.call($id)};
        } else {
            return #{fn.call($id, $num)};
        }
    }
}
```

**Comment by jasuperior** [comment]
this approach works (and i have used it), however there is one caveat: If i needed to match that expression on the head end of an infix macro, it throws an error:
```javascript
macro opt_lit {
    rule { $num:lit } => { $num }
    rule { } => {}
}

macro x {
    case infix { $num:opt_lit | _ $id:ident } => { 
        var opt = #{$num};
        if (opt.length === 0) {
            return #{fn.call($id)};
        } else {
            return #{fn.call($id, $num)};
        }
    }
}

56 x name
//error thrown
```

is there a way to make pattern classes match on the head of an infix?

**Comment by disnet** [comment]
Not currently. Maybe at some point but infix is tricky so have to be careful about what we allow there.
