### ISSUE TITLE
TypeScript comptibility

### ISSUE THREAD

**Issue by ghost** [mozilla/sweet.js#499]
I'm sorry for previous question. I change question. 
sweet.js support compiling to TypeScript, or not? 

How to compile redesign?

**Comment by disnet** [comment]
No, type script is not currently supported. See discussion at #482.

**Comment by acterhd** [comment]
I tried to recompile, but with npm install one package with error.

**Comment by disnet** [comment]
Which package failed?

**Comment by acterhd** [comment]
UNMET PEER DEPENDENCY immutable@>= 3
UNMET PEER DEPENDENCY eslint@>=0.20.0

**Comment by disnet** [comment]
I just made a bunch of changes to package.json. Are you still getting this? What version of npm are you on?
