### ISSUE TITLE
Cant invoke() ":" macro 

### ISSUE THREAD

**Issue by jasuperior** [mozilla/sweet.js#500]
I have a macro using the colon symbol which throws an error

here is a simplified version of what i am doing

```javascript
macro  (:)  {
    case { _ s $name } => {
        return #{ . $name }
    }
    rule {>}=>{:}
}

macro possession {
    rule { $patt:invoke(:) } => {
        $patt;
    }
}

possession person:s name 
```

```
SyntaxError: [macro] Macro `possession` could not be matched with `person : s name ...`
234: possession person:s name
```

although the macro works as aspected 
```
person:s name 
//person.name
```

this seems to be a problem with invoking any sort of symbol ```invoke(*), invoke(-)```. i've even tried making it literal ```invoke($[.])``` . is this just not allowed, or is it something that we can consider in future revisions?

**Comment by disnet** [comment]
We're probably doing an `isIdentifier` check when it should be `isIdentifier || isPunctuator`. I don't think there's any reason to not allow puntuators so we should probably fix this.

**Comment by jasuperior** [comment]
hey... i just wanted to mention a discovery. I noticed that there is a typo in the code i provided above. in the code that I'm using, ```(:)``` macro is declared with a ```let``` keyword. I noticed that when i changed it to the above ```macro``` declaration form, i can invoke it the same as any other macro. 

However, i wondered, if that was for any particular reason, or if it is a bug?

**Comment by disnet** [comment]
I'm mass closing issues due to the release of 1.0 obviating lots of bugs. If you feel this issue is something we still need to address feel free to reopen.
