### ISSUE TITLE
Headline example fails

### ISSUE THREAD

**Issue by rrthomas** [mozilla/sweet.js#502]
Using 1.0.0-alpha4, installed with npm, I just copied-and-pasted the `class` example from the home page as a sanity check, but got the following error:

    $ sjs -o output.js test.js
    /home/rrt/.local/lib/node_modules/sweet.js/dist/errors.js:25
        throw new Error("[assertion error]: " + message);
        ^
    
    Error: [assertion error]: cannot get the val of a delimiter

**Comment by disnet** [comment]
The redesign is not backwards compatible with 0.7.x (which is what is on the homepage) so not surprising that fails. The homepage will need to be updated when the redesign get's merged but we're not there just yet.

**Comment by rrthomas** [comment]
Thanks for the explanation.

Given that 1.0.0alphaX is the version installed by default by npm, could you change the home page for now so that the install instruction installs a version which works with the example given?

In fact, I'd probably be happy to use that myself for now, rather than wrestle with an alpha, so I'd be happy to know what branch/version to install myself.

**Comment by disnet** [comment]
Agh! I thought appending `-alpha` would exclude it from being installed without specifying the full version.

I guess I have to bump `0.7.4` to `1.0.0` to prevent this?

To get the officially released version in the meantime do `npm install sweet.js@0.7.x`.

**Comment by rrthomas** [comment]
Thanks for the workaround; apologies, I'm not up-to-date with npm myself, so I don't know how to fix this now or in general.

**Comment by disnet** [comment]
I have now learned about npm tags and fixed things so `npm install sweet.js` will get `0.7.x` instead of the alpha. Sorry for the confusion.

**Comment by rrthomas** [comment]
Awesome, thanks!
