### ISSUE TITLE
Cannot get sjs to produce output

### ISSUE THREAD

**Issue by rrthomas** [mozilla/sweet.js#503]
When I run sjs 1.0.0-alpha4, installed using npm, on an example I'm trying to whip up, it seems to process it successfully, but fails when it gets to the output stage:

    $ sjs -o fsmjs.js fsm.js
    fs.js:887
      return binding.lstat(pathModule._makeLong(path));
                     ^
    
    Error: ENOENT: no such file or directory, lstat '/home/rrt/Software/other/gorge-fsm/    '

It seems to have inserted 4 spaces at the end of the path it's complaining about.

**Comment by disnet** [comment]
Might be helpful to actually support the `-o` flag :)

Should work nowl

**Comment by rrthomas** [comment]
Thanks for your attention to this!

I now have 1.0.0alpha5. I get the following error:

    $ sjs -o fsmjs.js fsm.js
    /home/rrt/.local/lib/node_modules/sweet.js/bin/sjs:16
    var fname = argv._[0];
                    ^
    
    TypeError: Cannot read property '_' of undefined
        at Object.<anonymous> (/home/rrt/.local/lib/node_modules/sweet.js/bin/sjs:16:17)

**Comment by disnet** [comment]
Was using yargs wrong. Should work now.
