### ISSUE TITLE
redesign: cannot output `this`

### ISSUE THREAD

**Issue by tycho01** [mozilla/sweet.js#505]
I was trying the redesign branch, with this:
```
syntax test = function (ctx) {
  return #`this`;
}
test
```
Expected output: `this`. Actual output: `undefined`.

**Comment by disnet** [comment]
Actually, I just realized this is just the correct behavior of the babel backend. Sweet defaults to expanding a module and top-level `this` in a module is undefined as per the [spec](https://tc39.github.io/ecma262/#sec-module-environment-records-getthisbinding).

I just added a `--no-babel` flag to `sjs` if you don't want the babel backend to run.

**Comment by tycho01** [comment]
Hm, interesting, thank you for clarifying.

I suppose I may have been misinterpreting how things work -- I'd been under the impression #`this` would just kind of count as a literal string of code not due to have its contents (except `${}` interpolation) interpreted until run-time. If it is just resolved based on context, then fair enough though, that's admittedly just as good. 

I'm interested in the babel interop, since it's hard not to use it if only for `import`. I tried [forking](https://github.com/tycho01/sweetjs-loader) the webpack loader after noticing the existing one didn't play nice with the redesign yet, but if you've already explored using sweet/babel together, I'd be glad to learn more about how you've been approaching this. I think the docs were still devoid of babel mentions so far; I imagine others may be curious as well..

**Comment by disnet** [comment]
>  I'd been under the impression ``#`this` `` would just kind of count as a literal string of code

You have the right impression. The `test` macro expands to `this` just fine but then babel transforms the fully expanded source `this` to `undefined`. The same things happens if you run the following program through sweet:

```js
this // transformed by babel to undefined
```

> I think the docs were still devoid of babel mentions so far

Yep, on my list to write up. There's definitely some open questions there still. I'll open an issue once I write it up to get some feedback.
