### ISSUE TITLE
Is it possible to create an identifier from a string literal or vice versa?

### ISSUE THREAD

**Issue by thorn0** [mozilla/sweet.js#549]
I need to generate something like this:
```js
function Foo { return 'Foo'; }
```
I don't want to pass "Foo" to my macro twice (as an identifier and as a literal), but can't find any possibility to do this. Am I missing something? Also, am I right that there is no way to create a new identifier (e.g. `getFoo`) from an existing one?

**Comment by bopjesvla** [comment]
There's a `fromString` method on the Syntax class, which I assume will be available as a core module someday. You can use this hack to access it in the meantime:

```js
syntax def = ctx => {
	let ident = ctx.next().value,
		Syntax = #`;`.get(0).constructor,
		str = Syntax.fromString(ident.val())
	return #`function ${ident}() {
		let x = ${str};
		return x;
	}`
}
```

I'm using a helper variable because of #550.

**Comment by disnet** [comment]
(╯°□°）╯︵ ┻━┻

You go to all this work to hide internal APIs and people still find them!

Yeah, a proper API is coming soon but in the meantime you can use that hack. Just don't yell at me when I break it on a minor version bump 😝
